using System.Collections.Generic;
using BepInEx;
using BepInEx.Configuration;
using HarmonyLib;
using UnityEngine;

namespace BountyBoard
{
    /// <summary>
    /// A buildable Bounty Board. Build it with the hammer at a workbench like any other piece, then read the day's notices on it:
    /// hunt creatures, slay starred ones, or bring in loot, and get paid in coins. What it asks for follows how far you have got
    /// (each boss you beat opens the next region's creatures and loot), and hand-ins raise your rank, which raises the pay.
    ///
    /// Split across files: Plugin.cs (setup, registering the piece), ModelData.cs (the look, generated by tools/modelkit),
    /// ModelBuilder.cs and Look.cs (turning it into game objects), Icon.cs (the build-menu picture), Bounties.cs (the rules),
    /// Board.cs (the piece), Window.cs (the menu).
    /// </summary>
    [BepInPlugin(Guid, Name, Version)]
    public partial class Plugin : BaseUnityPlugin
    {
        public const string Guid = "com.dhack.bountyboard";
        public const string Name = "BountyBoard";
        public const string Version = "1.2.0";
        public const string PiecePrefab = "piece_bountyboard";

        internal static Plugin Instance;
        internal static DHack.Shared.ServerSettings Synced;   // the settings the server decides in multiplayer
        internal static ConfigEntry<int> RefreshDays, NoticesPerBoard, MaxActive, RewardPercent;
        internal static ConfigEntry<bool> ShowTracker;
        internal static ConfigEntry<float> TrackerX, TrackerY, TrackerScale;

        private static GameObject _holder, _prefab;
        private Harmony _harmony;

        private void Awake()
        {
            // These four are used by the host's game (it decides what is posted and what it pays); players are sent its values, so the
            // menu shows the host's limits.
            Synced = new DHack.Shared.ServerSettings(Guid, Config, Logger);
            RefreshDays = Synced.Add(Config.Bind("Notices", "DaysBetweenNewNotices", 1, new ConfigDescription("How many in-game days before the board posts new notices. In multiplayer the server's value applies.", new AcceptableValueRange<int>(1, 7))));
            NoticesPerBoard = Synced.Add(Config.Bind("Notices", "NoticesPerBoard", 5, new ConfigDescription("How many notices are posted. In multiplayer the server's value applies.", new AcceptableValueRange<int>(3, 8))));
            MaxActive = Synced.Add(Config.Bind("Contracts", "MostAtOnce", 3, new ConfigDescription("How many contracts the group can have going at once. A new one can only be taken when one is finished. In multiplayer the server's value applies.", new AcceptableValueRange<int>(1, 5))));
            RewardPercent = Synced.Add(Config.Bind("Contracts", "RewardPercent", 100, new ConfigDescription("Pay as a percentage of the standard rate (50 = half, 200 = double). In multiplayer the server's value applies.", new AcceptableValueRange<int>(10, 500))));
            // These are yours alone.
            ShowTracker = Config.Bind("Tracker", "ShowOnScreen", false, "Show the group's contracts and their progress on your screen (also a switch in the board's menu).");
            TrackerX = Config.Bind("Tracker", "X", 14f, "Distance from the left edge of the screen (UI pixels).");
            TrackerY = Config.Bind("Tracker", "Y", 330f, "Distance from the top of the screen (UI pixels).");
            TrackerScale = Config.Bind("Tracker", "Scale", 1f, new ConfigDescription("Size of the tracker.", new AcceptableValueRange<float>(0.6f, 2f)));

            Instance = this;
            _awakeFrame = Time.frameCount;
            _harmony = new Harmony(Guid);
            _harmony.PatchAll();
            if (ZNetScene.instance != null) Register(ZNetScene.instance); // hot reload while in a world
            Logger.LogInfo($"{Name} {Version} loaded");
        }

        private void OnDestroy()
        {
            Window.Close();
            UnregisterRpc();
            if (Instance == this) Instance = null;
            _harmony?.UnpatchSelf();
            Unregister();
            Styles.Destroy();
            Synced?.Dispose();
        }

        private void Update() { Synced?.Update(); UpdateNetwork(); Window.Tick(); }
        private void OnGUI() { Window.Draw(); Tracker.Draw(); }

        internal static void Register(ZNetScene scene)
        {
            GameObject source = scene.GetPrefab("piece_chest_wood");
            GameObject hammer = scene.GetPrefab("Hammer"); // items are in the scene too, and ObjectDB may not be awake yet
            GameObject bench = scene.GetPrefab("piece_workbench");
            if (source == null || hammer == null) { Debug.LogWarning(Name + ": chest or hammer prefab not found"); return; }

            if (_prefab == null)
            {
                _holder = new GameObject(Name + "Prefabs");
                _holder.SetActive(false); // keeps the copy from waking up as a real object
                Object.DontDestroyOnLoad(_holder);
                // the look never stops the piece being registered (without it, the host would delete the boards standing in the world)
                try { Look.Harvest(scene, source.GetComponentInChildren<Renderer>(true).sharedMaterial); }
                catch (System.Exception e) { Debug.LogWarning(Name + ": could not take the game's materials, the board looks plain: " + e.Message); }
                _prefab = Make(source, bench != null ? bench.GetComponent<CraftingStation>() : null);
            }

            var named = (Dictionary<int, GameObject>)AccessTools.Field(typeof(ZNetScene), "m_namedPrefabs").GetValue(scene);
            PieceTable table = hammer.GetComponent<ItemDrop>().m_itemData.m_shared.m_buildPieces;
            if (!scene.m_prefabs.Contains(_prefab)) scene.m_prefabs.Add(_prefab);
            named[_prefab.name.GetStableHashCode()] = _prefab; // lets it be placed and loaded from saves
            if (!table.m_pieces.Contains(_prefab)) table.m_pieces.Add(_prefab);
        }

        private static GameObject Make(GameObject source, CraftingStation workbench)
        {
            GameObject go = Object.Instantiate(source, _holder.transform);
            go.name = PiecePrefab;
            Container container = go.GetComponent<Container>();
            if (container != null) Object.DestroyImmediate(container); // it is not storage

            int layer = LayerMask.NameToLayer("piece");
            if (layer < 0) layer = go.layer;
            foreach (Renderer r in go.GetComponentsInChildren<Renderer>(true)) r.enabled = false; // hide the chest
            foreach (Collider c in go.GetComponentsInChildren<Collider>(true)) Object.DestroyImmediate(c); // and its hitbox
            var hit = new GameObject("Hitbox") { layer = layer };
            hit.transform.SetParent(go.transform, false);
            var box = hit.AddComponent<BoxCollider>();
            box.center = new Vector3(0f, 1.5f, 0f);
            box.size = new Vector3(2.7f, 3.0f, 1.0f);

            try { ModelBuilder.Build(go.transform, ModelData.Parts, go.layer); }
            catch (System.Exception e) { Debug.LogWarning(Name + ": could not build the board's model: " + e.Message); }

            Piece piece = go.GetComponent<Piece>();
            piece.m_name = "Bounty Board";
            piece.m_description = "Posts a few jobs every day: hunt creatures, slay starred ones or bring in loot, and get paid in coins. Finish more to rank up and earn more.";
            piece.m_category = Piece.PieceCategory.Misc;
            piece.m_craftingStation = workbench;
            piece.m_resources = new[] { Req("Wood", 20), Req("LeatherScraps", 6), Req("Flint", 4) };
            try { piece.m_icon = Icon.Make(go); }
            catch (System.Exception e) { Debug.LogWarning(Name + ": could not draw the build-menu picture: " + e.Message); }
            go.AddComponent<BountyBoardStation>();
            return go;
        }

        internal static void Unregister()
        {
            if (_prefab == null) return;
            if (ZNetScene.instance != null)
            {
                ZNetScene.instance.m_prefabs.Remove(_prefab);
                var named = (Dictionary<int, GameObject>)AccessTools.Field(typeof(ZNetScene), "m_namedPrefabs").GetValue(ZNetScene.instance);
                int hash = _prefab.name.GetStableHashCode();
                if (named.TryGetValue(hash, out GameObject current) && current == _prefab) named.Remove(hash); // only our own entry
            }
            GameObject hammer = ObjectDB.instance != null ? ObjectDB.instance.GetItemPrefab("Hammer") : null;
            if (hammer != null) hammer.GetComponent<ItemDrop>().m_itemData.m_shared.m_buildPieces.m_pieces.Remove(_prefab);
            _prefab = null;
            Object.Destroy(_holder);
            _holder = null;
            Look.Clear();
        }

        private static Piece.Requirement Req(string item, int amount)
        {
            GameObject go = ZNetScene.instance != null ? ZNetScene.instance.GetPrefab(item) : null;
            if (go == null && ObjectDB.instance != null) go = ObjectDB.instance.GetItemPrefab(item);
            return new Piece.Requirement { m_resItem = go != null ? go.GetComponent<ItemDrop>() : null, m_amount = amount, m_recover = true };
        }
    }

    // You land the last blow on something: the host counts it for the group's contracts.
    [HarmonyPatch(typeof(Character), nameof(Character.OnDeath))]
    internal static class Character_OnDeath
    {
        private static void Prefix(Character __instance) => Plugin.Instance?.ReportKill(__instance);
    }

    [HarmonyPatch(typeof(ZNetScene), "Awake")]
    internal static class ZNetScene_Awake
    {
        private static void Postfix(ZNetScene __instance) => Plugin.Register(__instance);
    }

    // Whichever of ZNetScene and ObjectDB wakes second, the piece is registered before any saved one is loaded.
    [HarmonyPatch(typeof(ObjectDB), "Awake")]
    internal static class ObjectDB_Awake
    {
        private static void Postfix() { if (ZNetScene.instance != null) Plugin.Register(ZNetScene.instance); }
    }

    // While the menu is open: keep the game from reacting to clicks and typing, show the mouse, and let Escape close only the menu.
    [HarmonyPatch(typeof(PlayerController), "TakeInput")]
    internal static class PlayerController_TakeInput
    {
        private static void Postfix(ref bool __result) { if (Window.IsOpen) __result = false; }
    }

    [HarmonyPatch(typeof(Player), "TakeInput")]
    internal static class Player_TakeInput
    {
        private static void Postfix(ref bool __result) { if (Window.IsOpen) __result = false; }
    }

    [HarmonyPatch(typeof(GameCamera), nameof(GameCamera.UpdateMouseCapture))]
    internal static class GameCamera_UpdateMouseCapture
    {
        private static bool Prefix()
        {
            if (!Window.IsOpen) return true;
            ZCursor.LockState = CursorLockMode.None;
            ZCursor.Show();
            return false;
        }
    }

    [HarmonyPatch(typeof(ZInput), nameof(ZInput.GetMouseScrollWheel))]
    internal static class ZInput_GetMouseScrollWheel
    {
        private static void Postfix(ref float __result) { if (Window.IsOpen) __result = 0f; }
    }

    [HarmonyPatch(typeof(Menu), "Update")]
    internal static class Menu_Update_EscapeCloses
    {
        private static bool Prefix()
        {
            if (!Window.IsOpen) return true;
            if (!(ZInput.GetKeyDown(KeyCode.Escape) || ZInput.GetButtonDown("JoyMenu"))) return true;
            Window.Close();
            return false;
        }
    }
}
