using System.Collections.Generic;
using BepInEx;
using BepInEx.Configuration;
using HarmonyLib;
using UnityEngine;

namespace BountyBoard
{
    /// <summary>
    /// A buildable Bounty Board. Build it with the hammer at a workbench like any other piece, then read the day's notices on it:
    /// hunt creatures, slay starred ones, or bring in loot, and get paid in coins. What it asks for follows how far you have got
    /// (each boss you beat opens the next region's creatures and loot), and hand-ins raise your rank, which raises the pay.
    ///
    /// Split across files: Plugin.cs (setup, registering the piece), ModelData.cs (the look, generated by tools/modelkit),
    /// ModelBuilder.cs and Look.cs (turning it into game objects), Icon.cs (the build-menu picture), Bounties.cs (the rules),
    /// Board.cs (the piece), Window.cs (the menu).
    /// </summary>
    [BepInPlugin(Guid, Name, Version)]
    public class Plugin : BaseUnityPlugin
    {
        public const string Guid = "com.dhack.bountyboard";
        public const string Name = "BountyBoard";
        public const string Version = "1.0.0";
        public const string PiecePrefab = "piece_bountyboard";

        internal static ConfigEntry<int> RefreshDays, NoticesPerBoard, MaxActive, RewardPercent;

        private static GameObject _holder, _prefab;
        private Harmony _harmony;

        private void Awake()
        {
            RefreshDays = Config.Bind("Notices", "DaysBetweenNewNotices", 1, new ConfigDescription("How many in-game days before a board posts new notices.", new AcceptableValueRange<int>(1, 7)));
            NoticesPerBoard = Config.Bind("Notices", "NoticesPerBoard", 4, new ConfigDescription("How many notices a board shows (the last one is always for starred creatures, the one before it for loot).", new AcceptableValueRange<int>(2, 8)));
            MaxActive = Config.Bind("Contracts", "MostAtOnce", 5, new ConfigDescription("How many contracts you can carry at once.", new AcceptableValueRange<int>(1, 12)));
            RewardPercent = Config.Bind("Contracts", "RewardPercent", 100, new ConfigDescription("Pay as a percentage of the standard rate (50 = half, 200 = double).", new AcceptableValueRange<int>(10, 500)));

            _harmony = new Harmony(Guid);
            _harmony.PatchAll();
            if (ZNetScene.instance != null) Register(ZNetScene.instance); // hot reload while in a world
            Logger.LogInfo($"{Name} {Version} loaded");
        }

        private void OnDestroy()
        {
            Window.Close();
            _harmony?.UnpatchSelf();
            Unregister();
            Styles.Destroy();
        }

        private void Update() => Window.Tick();
        private void OnGUI() => Window.Draw();

        internal static void Register(ZNetScene scene)
        {
            if (ObjectDB.instance == null) return;
            GameObject source = scene.GetPrefab("piece_chest_wood");
            GameObject hammer = ObjectDB.instance.GetItemPrefab("Hammer");
            GameObject bench = scene.GetPrefab("piece_workbench");
            if (source == null || hammer == null) { Debug.LogWarning(Name + ": chest or hammer prefab not found"); return; }

            if (_prefab == null)
            {
                _holder = new GameObject(Name + "Prefabs");
                _holder.SetActive(false); // keeps the copy from waking up as a real object
                Object.DontDestroyOnLoad(_holder);
                Look.Harvest(scene, source.GetComponentInChildren<Renderer>(true).sharedMaterial);
                _prefab = Make(source, bench != null ? bench.GetComponent<CraftingStation>() : null);
            }

            var named = (Dictionary<int, GameObject>)AccessTools.Field(typeof(ZNetScene), "m_namedPrefabs").GetValue(scene);
            PieceTable table = hammer.GetComponent<ItemDrop>().m_itemData.m_shared.m_buildPieces;
            if (!scene.m_prefabs.Contains(_prefab)) scene.m_prefabs.Add(_prefab);
            named[_prefab.name.GetStableHashCode()] = _prefab; // lets it be placed and loaded from saves
            if (!table.m_pieces.Contains(_prefab)) table.m_pieces.Add(_prefab);
        }

        private static GameObject Make(GameObject source, CraftingStation workbench)
        {
            GameObject go = Object.Instantiate(source, _holder.transform);
            go.name = PiecePrefab;
            Container container = go.GetComponent<Container>();
            if (container != null) Object.DestroyImmediate(container); // it is not storage

            int layer = LayerMask.NameToLayer("piece");
            if (layer < 0) layer = go.layer;
            foreach (Renderer r in go.GetComponentsInChildren<Renderer>(true)) r.enabled = false; // hide the chest
            foreach (Collider c in go.GetComponentsInChildren<Collider>(true)) Object.DestroyImmediate(c); // and its hitbox
            var hit = new GameObject("Hitbox") { layer = layer };
            hit.transform.SetParent(go.transform, false);
            var box = hit.AddComponent<BoxCollider>();
            box.center = new Vector3(0f, 1.5f, 0f);
            box.size = new Vector3(2.7f, 3.0f, 1.0f);

            ModelBuilder.Build(go.transform, ModelData.Parts, go.layer);

            Piece piece = go.GetComponent<Piece>();
            piece.m_name = "Bounty Board";
            piece.m_description = "Posts a few jobs every day: hunt creatures, slay starred ones or bring in loot, and get paid in coins. Finish more to rank up and earn more.";
            piece.m_category = Piece.PieceCategory.Misc;
            piece.m_craftingStation = workbench;
            piece.m_resources = new[] { Req("Wood", 20), Req("LeatherScraps", 6), Req("Flint", 4) };
            piece.m_icon = Icon.Make(go);
            go.AddComponent<BountyBoardStation>();
            return go;
        }

        internal static void Unregister()
        {
            if (_prefab == null) return;
            if (ZNetScene.instance != null)
            {
                ZNetScene.instance.m_prefabs.Remove(_prefab);
                ((Dictionary<int, GameObject>)AccessTools.Field(typeof(ZNetScene), "m_namedPrefabs").GetValue(ZNetScene.instance)).Remove(_prefab.name.GetStableHashCode());
            }
            GameObject hammer = ObjectDB.instance != null ? ObjectDB.instance.GetItemPrefab("Hammer") : null;
            if (hammer != null) hammer.GetComponent<ItemDrop>().m_itemData.m_shared.m_buildPieces.m_pieces.Remove(_prefab);
            _prefab = null;
            Object.Destroy(_holder);
            _holder = null;
            Look.Clear();
        }

        private static Piece.Requirement Req(string item, int amount)
        {
            GameObject go = ObjectDB.instance.GetItemPrefab(item);
            return new Piece.Requirement { m_resItem = go != null ? go.GetComponent<ItemDrop>() : null, m_amount = amount, m_recover = true };
        }
    }

    [HarmonyPatch(typeof(ZNetScene), "Awake")]
    internal static class ZNetScene_Awake
    {
        private static void Postfix(ZNetScene __instance) => Plugin.Register(__instance);
    }

    // While the menu is open: keep the game from reacting to clicks and typing, show the mouse, and let Escape close only the menu.
    [HarmonyPatch(typeof(PlayerController), "TakeInput")]
    internal static class PlayerController_TakeInput
    {
        private static void Postfix(ref bool __result) { if (Window.IsOpen) __result = false; }
    }

    [HarmonyPatch(typeof(Player), "TakeInput")]
    internal static class Player_TakeInput
    {
        private static void Postfix(ref bool __result) { if (Window.IsOpen) __result = false; }
    }

    [HarmonyPatch(typeof(GameCamera), nameof(GameCamera.UpdateMouseCapture))]
    internal static class GameCamera_UpdateMouseCapture
    {
        private static bool Prefix()
        {
            if (!Window.IsOpen) return true;
            ZCursor.LockState = CursorLockMode.None;
            ZCursor.Show();
            return false;
        }
    }

    [HarmonyPatch(typeof(ZInput), nameof(ZInput.GetMouseScrollWheel))]
    internal static class ZInput_GetMouseScrollWheel
    {
        private static void Postfix(ref float __result) { if (Window.IsOpen) __result = 0f; }
    }

    [HarmonyPatch(typeof(Menu), "Update")]
    internal static class Menu_Update_EscapeCloses
    {
        private static bool Prefix()
        {
            if (!Window.IsOpen) return true;
            if (!(ZInput.GetKeyDown(KeyCode.Escape) || ZInput.GetButtonDown("JoyMenu"))) return true;
            Window.Close();
            return false;
        }
    }
}
