// <auto-generated> by tools/modelkit. Edit the model script and regenerate; do not edit by hand. </auto-generated>
namespace CigarSmoking
{
    internal static class M_barrel
    {
        internal const float Scale = 1f;
        // name, shape, parent group (or ""), x, y, z, scale x, y, z, euler x, y, z, material
        internal static readonly object[][] Parts =
        {
            new object[] { "body", "Cylinder", "", 0f, 0.44f, 0f, 0.74f, 0.44f, 0.74f, 0f, 0f, 0f, "Cedar" },
            new object[] { "belly", "Cylinder", "", 0f, 0.44f, 0f, 0.777f, 0.264f, 0.777f, 0f, 0f, 0f, "Cedar" },
            new object[] { "hoop", "Cylinder", "", 0f, 0.12f, 0f, 0.7548f, 0.022f, 0.7548f, 0f, 0f, 0f, "Iron" },
            new object[] { "hoop", "Cylinder", "", 0f, 0.34f, 0f, 0.7992f, 0.022f, 0.7992f, 0f, 0f, 0f, "Iron" },
            new object[] { "hoop", "Cylinder", "", 0f, 0.54f, 0f, 0.7992f, 0.022f, 0.7992f, 0f, 0f, 0f, "Iron" },
            new object[] { "hoop", "Cylinder", "", 0f, 0.76f, 0f, 0.7548f, 0.022f, 0.7548f, 0f, 0f, 0f, "Iron" },
            new object[] { "stave", "Cube", "", 0f, 0.44f, 0.3737f, 0.012f, 0.792f, 0.02f, 0f, 0f, 0f, "CedarDark" },
            new object[] { "stave", "Cube", "", 0.1868f, 0.44f, 0.3236f, 0.012f, 0.792f, 0.02f, 0f, 30f, 0f, "CedarDark" },
            new object[] { "stave", "Cube", "", 0.3236f, 0.44f, 0.1869f, 0.012f, 0.792f, 0.02f, 0f, 60f, 0f, "CedarDark" },
            new object[] { "stave", "Cube", "", 0.3737f, 0.44f, 0f, 0.012f, 0.792f, 0.02f, 0f, 90f, 0f, "CedarDark" },
            new object[] { "stave", "Cube", "", 0.3236f, 0.44f, -0.1868f, 0.012f, 0.792f, 0.02f, 0f, 120f, 0f, "CedarDark" },
            new object[] { "stave", "Cube", "", 0.1868f, 0.44f, -0.3236f, 0.012f, 0.792f, 0.02f, 0f, 150f, 0f, "CedarDark" },
            new object[] { "stave", "Cube", "", 0f, 0.44f, -0.3737f, 0.012f, 0.792f, 0.02f, 0f, 180f, 0f, "CedarDark" },
            new object[] { "stave", "Cube", "", -0.1869f, 0.44f, -0.3236f, 0.012f, 0.792f, 0.02f, 0f, 210f, 0f, "CedarDark" },
            new object[] { "stave", "Cube", "", -0.3236f, 0.44f, -0.1869f, 0.012f, 0.792f, 0.02f, 0f, 240f, 0f, "CedarDark" },
            new object[] { "stave", "Cube", "", -0.3737f, 0.44f, 0f, 0.012f, 0.792f, 0.02f, 0f, 270f, 0f, "CedarDark" },
            new object[] { "stave", "Cube", "", -0.3236f, 0.44f, 0.1869f, 0.012f, 0.792f, 0.02f, 0f, 300f, 0f, "CedarDark" },
            new object[] { "stave", "Cube", "", -0.1869f, 0.44f, 0.3236f, 0.012f, 0.792f, 0.02f, 0f, 330f, 0f, "CedarDark" },
            new object[] { "rim", "Cylinder", "", 0f, 0.89f, 0f, 0.74f, 0.015f, 0.74f, 0f, 0f, 0f, "CedarDark" },
            new object[] { "tap", "Cylinder", "", 0f, 0.2f, -0.42f, 0.05f, 0.06f, 0.05f, 90f, 0f, 0f, "Brass" },
            new object[] { "tapHandle", "Cylinder", "", 0f, 0.2f, -0.48f, 0.07f, 0.012f, 0.012f, 0f, 0f, 90f, "Brass" },
            new object[] { "handle", "Cylinder", "", -0.385f, 0.74f, 0f, 0.03f, 0.06f, 0.03f, 0f, 0f, -90f, "Twine" },
            new object[] { "handle", "Cylinder", "", 0.385f, 0.74f, 0f, 0.03f, 0.06f, 0.03f, 0f, 0f, 90f, "Twine" },
            new object[] { "contents", "Group", "", 0f, 0f, 0f, 1f, 1f, 1f, 0f, 0f, 0f, "" },
            new object[] { "heapLeaf", "Leaf", "contents", 0f, 0.9001f, 0.0223f, 0.15f, 0.594f, 0.36f, -50f, 0f, 0f, "LeafAged" },
            new object[] { "heapLeafRib", "Rib", "contents", 0f, 0.9001f, 0.0223f, 0.15f, 0.594f, 0.36f, -50f, 0f, 0f, "LeafAgedRib" },
            new object[] { "heapLeaf", "Leaf", "contents", 0.0143f, 0.9001f, 0.0171f, 0.15f, 0.594f, 0.36f, -50f, 40f, 0f, "LeafAged" },
            new object[] { "heapLeafRib", "Rib", "contents", 0.0143f, 0.9001f, 0.0171f, 0.15f, 0.594f, 0.36f, -50f, 40f, 0f, "LeafAgedRib" },
            new object[] { "heapLeaf", "Leaf", "contents", 0.022f, 0.9001f, 0.0039f, 0.15f, 0.594f, 0.36f, -50f, 80f, 0f, "LeafAged" },
            new object[] { "heapLeafRib", "Rib", "contents", 0.022f, 0.9001f, 0.0039f, 0.15f, 0.594f, 0.36f, -50f, 80f, 0f, "LeafAgedRib" },
            new object[] { "heapLeaf", "Leaf", "contents", 0.0193f, 0.9001f, -0.0111f, 0.15f, 0.594f, 0.36f, -50f, 120f, 0f, "LeafAged" },
            new object[] { "heapLeafRib", "Rib", "contents", 0.0193f, 0.9001f, -0.0111f, 0.15f, 0.594f, 0.36f, -50f, 120f, 0f, "LeafAgedRib" },
            new object[] { "heapLeaf", "Leaf", "contents", 0.0076f, 0.9001f, -0.0209f, 0.15f, 0.594f, 0.36f, -50f, 160f, 0f, "LeafAged" },
            new object[] { "heapLeafRib", "Rib", "contents", 0.0076f, 0.9001f, -0.0209f, 0.15f, 0.594f, 0.36f, -50f, 160f, 0f, "LeafAgedRib" },
            new object[] { "heapLeaf", "Leaf", "contents", -0.0076f, 0.9001f, -0.0209f, 0.15f, 0.594f, 0.36f, -50f, 200f, 0f, "LeafAged" },
            new object[] { "heapLeafRib", "Rib", "contents", -0.0076f, 0.9001f, -0.0209f, 0.15f, 0.594f, 0.36f, -50f, 200f, 0f, "LeafAgedRib" },
            new object[] { "heapLeaf", "Leaf", "contents", -0.0193f, 0.9001f, -0.0111f, 0.15f, 0.594f, 0.36f, -50f, 240f, 0f, "LeafAged" },
            new object[] { "heapLeafRib", "Rib", "contents", -0.0193f, 0.9001f, -0.0111f, 0.15f, 0.594f, 0.36f, -50f, 240f, 0f, "LeafAgedRib" },
            new object[] { "heapLeaf", "Leaf", "contents", -0.022f, 0.9001f, 0.0039f, 0.15f, 0.594f, 0.36f, -50f, 280f, 0f, "LeafAged" },
            new object[] { "heapLeafRib", "Rib", "contents", -0.022f, 0.9001f, 0.0039f, 0.15f, 0.594f, 0.36f, -50f, 280f, 0f, "LeafAgedRib" },
            new object[] { "heapLeaf", "Leaf", "contents", -0.0143f, 0.9001f, 0.0171f, 0.15f, 0.594f, 0.36f, -50f, 320f, 0f, "LeafAged" },
            new object[] { "heapLeafRib", "Rib", "contents", -0.0143f, 0.9001f, 0.0171f, 0.15f, 0.594f, 0.36f, -50f, 320f, 0f, "LeafAgedRib" },
            new object[] { "lidOn", "Group", "", 0f, 0f, 0f, 1f, 1f, 1f, 0f, 0f, 0f, "" },
            new object[] { "lid", "Cylinder", "lidOn", 0.02f, 0.93f, 0f, 0.703f, 0.025f, 0.703f, 4f, 0f, 0f, "Cedar" },
            new object[] { "lidBatten", "Cube", "lidOn", 0.02f, 0.965f, 0f, 0.5f, 0.025f, 0.07f, 0f, 0f, 0f, "CedarDark" },
            new object[] { "lidKnob", "Sphere", "lidOn", 0.02f, 0.995f, 0f, 0.07f, 0.05f, 0.07f, 0f, 0f, 0f, "Brass" },
        };
    }
}
