// <auto-generated> by tools/modelkit. Edit the model script and regenerate; do not edit by hand. </auto-generated>
namespace CigarSmoking
{
    internal static class M_humidor
    {
        internal const float Scale = 1f;
        // name, shape, parent group (or ""), x, y, z, scale x, y, z, euler x, y, z, material
        internal static readonly object[][] Parts =
        {
            new object[] { "foot", "Cube", "", -0.24f, 0.05f, -0.17f, 0.07f, 0.1f, 0.07f, 0f, 0f, 0f, "CedarDark" },
            new object[] { "foot", "Cube", "", -0.24f, 0.05f, 0.17f, 0.07f, 0.1f, 0.07f, 0f, 0f, 0f, "CedarDark" },
            new object[] { "foot", "Cube", "", 0.24f, 0.05f, -0.17f, 0.07f, 0.1f, 0.07f, 0f, 0f, 0f, "CedarDark" },
            new object[] { "foot", "Cube", "", 0.24f, 0.05f, 0.17f, 0.07f, 0.1f, 0.07f, 0f, 0f, 0f, "CedarDark" },
            new object[] { "body", "Cube", "", 0f, 0.38f, 0f, 0.56f, 0.56f, 0.42f, 0f, 0f, 0f, "Cedar" },
            new object[] { "plinth", "Cube", "", 0f, 0.12f, 0f, 0.59f, 0.04f, 0.45f, 0f, 0f, 0f, "CedarDark" },
            new object[] { "lid", "Cube", "", 0f, 0.71f, 0f, 0.6f, 0.05f, 0.46f, 0f, 0f, 0f, "CedarDark" },
            new object[] { "lidTop", "Cube", "", 0f, 0.745f, 0f, 0.5f, 0.02f, 0.36f, 0f, 0f, 0f, "Cedar" },
            new object[] { "door", "Cube", "", 0f, 0.38f, -0.216f, 0.46f, 0.48f, 0.02f, 0f, 0f, 0f, "CedarDark" },
            new object[] { "panel", "Cube", "", 0f, 0.38f, -0.23f, 0.36f, 0.36f, 0.012f, 0f, 0f, 0f, "Cedar" },
            new object[] { "latch", "Sphere", "", 0.18f, 0.38f, -0.245f, 0.045f, 0.045f, 0.02f, 0f, 0f, 0f, "Brass" },
            new object[] { "hygrometer", "Cylinder", "", -0.14f, 0.52f, -0.245f, 0.1f, 0.012f, 0.1f, 90f, 0f, 0f, "Brass" },
            new object[] { "hygroFace", "Cylinder", "", -0.14f, 0.52f, -0.255f, 0.08f, 0.006f, 0.08f, 90f, 0f, 0f, "Cream" },
            new object[] { "hinge", "Cube", "", 0.24f, 0.22f, -0.23f, 0.025f, 0.07f, 0.015f, 0f, 0f, 0f, "Brass" },
            new object[] { "hinge", "Cube", "", 0.24f, 0.52f, -0.23f, 0.025f, 0.07f, 0.015f, 0f, 0f, 0f, "Brass" },
            new object[] { "cigarOnLid", "Cylinder", "", -0.1f, 0.772f, 0.02f, 0.026f, 0.08f, 0.026f, 0f, 12f, 90f, "Body_maduro" },
            new object[] { "cigarBandOnLid", "Cylinder", "", -0.07f, 0.772f, 0.017f, 0.029f, 0.011f, 0.029f, 0f, 12f, 90f, "Band_maduro" },
        };
    }
}
