// <auto-generated> by tools/modelkit. Edit the model script and regenerate; do not edit by hand. </auto-generated>
namespace CigarSmoking
{
    internal static class M_leaf_forest_aged
    {
        internal const float Scale = 1f;
        // name, shape, parent group (or ""), x, y, z, scale x, y, z, euler x, y, z, material
        internal static readonly object[][] Parts =
        {
            new object[] { "leaf", "Leaf", "", 0f, 0.03f, -0.14f, 0.1088f, 0.648f, 0.32f, -16f, -47.5f, 0f, "Aged_forest" },
            new object[] { "leafRib", "Rib", "", 0f, 0.03f, -0.14f, 0.1088f, 0.648f, 0.32f, -16f, -47.5f, 0f, "AgedRib_forest" },
            new object[] { "leaf", "Leaf", "", 0f, 0.036f, -0.14f, 0.1088f, 0.648f, 0.32f, -12f, -28.5f, 0f, "Aged_forest" },
            new object[] { "leafRib", "Rib", "", 0f, 0.036f, -0.14f, 0.1088f, 0.648f, 0.32f, -12f, -28.5f, 0f, "AgedRib_forest" },
            new object[] { "leaf", "Leaf", "", 0f, 0.042f, -0.14f, 0.1088f, 0.648f, 0.32f, -8f, -9.5f, 0f, "Aged_forest" },
            new object[] { "leafRib", "Rib", "", 0f, 0.042f, -0.14f, 0.1088f, 0.648f, 0.32f, -8f, -9.5f, 0f, "AgedRib_forest" },
            new object[] { "leaf", "Leaf", "", 0f, 0.03f, -0.14f, 0.1088f, 0.648f, 0.32f, -16f, 9.5f, 0f, "Aged_forest" },
            new object[] { "leafRib", "Rib", "", 0f, 0.03f, -0.14f, 0.1088f, 0.648f, 0.32f, -16f, 9.5f, 0f, "AgedRib_forest" },
            new object[] { "leaf", "Leaf", "", 0f, 0.036f, -0.14f, 0.1088f, 0.648f, 0.32f, -12f, 28.5f, 0f, "Aged_forest" },
            new object[] { "leafRib", "Rib", "", 0f, 0.036f, -0.14f, 0.1088f, 0.648f, 0.32f, -12f, 28.5f, 0f, "AgedRib_forest" },
            new object[] { "leaf", "Leaf", "", 0f, 0.042f, -0.14f, 0.1088f, 0.648f, 0.32f, -8f, 47.5f, 0f, "Aged_forest" },
            new object[] { "leafRib", "Rib", "", 0f, 0.042f, -0.14f, 0.1088f, 0.648f, 0.32f, -8f, 47.5f, 0f, "AgedRib_forest" },
            new object[] { "twine", "Cylinder", "", 0f, 0.042f, -0.115f, 0.05f, 0.022f, 0.05f, 90f, 0f, 0f, "Twine" },
        };
    }
}
