// <auto-generated> by tools/modelkit. Edit the model script and regenerate; do not edit by hand. </auto-generated>
namespace CigarSmoking
{
    internal static class M_plant_plains_growing
    {
        internal const float Scale = 1f;
        // name, shape, parent group (or ""), x, y, z, scale x, y, z, euler x, y, z, material
        internal static readonly object[][] Parts =
        {
            new object[] { "stalk", "Cylinder", "", 0f, 0.25f, 0f, 0.024f, 0.25f, 0.024f, 0f, 0f, 0f, "Stalk" },
            new object[] { "leaf", "Leaf", "", 0f, 0.05f, 0f, 0.2078f, 0.5565f, 0.371f, 34f, 0f, 0f, "LeafB_plains" },
            new object[] { "leafRib", "Rib", "", 0f, 0.05f, 0f, 0.2078f, 0.5565f, 0.371f, 34f, 0f, 0f, "Rib_plains" },
            new object[] { "leaf", "Leaf", "", 0f, 0.087f, 0f, 0.2169f, 0.581f, 0.3873f, 32f, 137.5f, 0f, "Leaf_plains" },
            new object[] { "leafRib", "Rib", "", 0f, 0.087f, 0f, 0.2169f, 0.581f, 0.3873f, 32f, 137.5f, 0f, "Rib_plains" },
            new object[] { "leaf", "Leaf", "", 0f, 0.124f, 0f, 0.2261f, 0.6055f, 0.4037f, 30f, 275f, 0f, "LeafB_plains" },
            new object[] { "leafRib", "Rib", "", 0f, 0.124f, 0f, 0.2261f, 0.6055f, 0.4037f, 30f, 275f, 0f, "Rib_plains" },
            new object[] { "leaf", "Leaf", "", 0f, 0.161f, 0f, 0.2352f, 0.63f, 0.42f, 28f, 412.5f, 0f, "Leaf_plains" },
            new object[] { "leafRib", "Rib", "", 0f, 0.161f, 0f, 0.2352f, 0.63f, 0.42f, 28f, 412.5f, 0f, "Rib_plains" },
            new object[] { "leaf", "Leaf", "", 0f, 0.198f, 0f, 0.2261f, 0.6055f, 0.4037f, 26f, 550f, 0f, "LeafB_plains" },
            new object[] { "leafRib", "Rib", "", 0f, 0.198f, 0f, 0.2261f, 0.6055f, 0.4037f, 26f, 550f, 0f, "Rib_plains" },
            new object[] { "leaf", "Leaf", "", 0f, 0.235f, 0f, 0.2169f, 0.581f, 0.3873f, 24f, 687.5f, 0f, "Leaf_plains" },
            new object[] { "leafRib", "Rib", "", 0f, 0.235f, 0f, 0.2169f, 0.581f, 0.3873f, 24f, 687.5f, 0f, "Rib_plains" },
            new object[] { "leaf", "Leaf", "", 0f, 0.272f, 0f, 0.2078f, 0.5565f, 0.371f, 22f, 825f, 0f, "LeafB_plains" },
            new object[] { "leafRib", "Rib", "", 0f, 0.272f, 0f, 0.2078f, 0.5565f, 0.371f, 22f, 825f, 0f, "Rib_plains" },
            new object[] { "leaf", "Leaf", "", 0f, 0.309f, 0f, 0.1986f, 0.532f, 0.3547f, 20f, 962.5f, 0f, "Leaf_plains" },
            new object[] { "leafRib", "Rib", "", 0f, 0.309f, 0f, 0.1986f, 0.532f, 0.3547f, 20f, 962.5f, 0f, "Rib_plains" },
            new object[] { "leaf", "Leaf", "", 0f, 0.346f, 0f, 0.1895f, 0.5075f, 0.3383f, 18f, 1100f, 0f, "LeafB_plains" },
            new object[] { "leafRib", "Rib", "", 0f, 0.346f, 0f, 0.1895f, 0.5075f, 0.3383f, 18f, 1100f, 0f, "Rib_plains" },
            new object[] { "leaf", "Leaf", "", 0f, 0.383f, 0f, 0.1803f, 0.483f, 0.322f, 16f, 1237.5f, 0f, "Leaf_plains" },
            new object[] { "leafRib", "Rib", "", 0f, 0.383f, 0f, 0.1803f, 0.483f, 0.322f, 16f, 1237.5f, 0f, "Rib_plains" },
            new object[] { "leaf", "Leaf", "", 0f, 0.42f, 0f, 0.1712f, 0.4585f, 0.3057f, 14f, 1375f, 0f, "LeafB_plains" },
            new object[] { "leafRib", "Rib", "", 0f, 0.42f, 0f, 0.1712f, 0.4585f, 0.3057f, 14f, 1375f, 0f, "Rib_plains" },
        };
    }
}
