// <auto-generated> by tools/modelkit. Edit the model script and regenerate; do not edit by hand. </auto-generated>
namespace CigarSmoking
{
    internal static class M_plant_plains_seedling_sick
    {
        internal const float Scale = 1f;
        // name, shape, parent group (or ""), x, y, z, scale x, y, z, euler x, y, z, material
        internal static readonly object[][] Parts =
        {
            new object[] { "stalk", "Cylinder", "", 0f, 0.03f, 0f, 0.012f, 0.03f, 0.012f, 0f, 0f, 0f, "Stalk" },
            new object[] { "leaf", "Leaf", "", 0f, 0.02f, 0f, 0.075f, 0.21f, 0.14f, 38f, 0f, 0f, "LeafSick" },
            new object[] { "leafRib", "Rib", "", 0f, 0.02f, 0f, 0.075f, 0.21f, 0.14f, 38f, 0f, 0f, "RibSick" },
            new object[] { "leaf", "Leaf", "", 0f, 0.04f, 0f, 0.075f, 0.2325f, 0.155f, 38f, 137.5f, 0f, "LeafSick" },
            new object[] { "leafRib", "Rib", "", 0f, 0.04f, 0f, 0.075f, 0.2325f, 0.155f, 38f, 137.5f, 0f, "RibSick" },
            new object[] { "leaf", "Leaf", "", 0f, 0.02f, 0f, 0.075f, 0.255f, 0.17f, 38f, 275f, 0f, "LeafSick" },
            new object[] { "leafRib", "Rib", "", 0f, 0.02f, 0f, 0.075f, 0.255f, 0.17f, 38f, 275f, 0f, "RibSick" },
            new object[] { "leaf", "Leaf", "", 0f, 0.04f, 0f, 0.075f, 0.21f, 0.14f, 38f, 412.5f, 0f, "LeafSick" },
            new object[] { "leafRib", "Rib", "", 0f, 0.04f, 0f, 0.075f, 0.21f, 0.14f, 38f, 412.5f, 0f, "RibSick" },
            new object[] { "leaf", "Leaf", "", 0f, 0.02f, 0f, 0.075f, 0.2325f, 0.155f, 38f, 550f, 0f, "LeafSick" },
            new object[] { "leafRib", "Rib", "", 0f, 0.02f, 0f, 0.075f, 0.2325f, 0.155f, 38f, 550f, 0f, "RibSick" },
            new object[] { "leaf", "Leaf", "", 0f, 0.04f, 0f, 0.075f, 0.255f, 0.17f, 38f, 687.5f, 0f, "LeafSick" },
            new object[] { "leafRib", "Rib", "", 0f, 0.04f, 0f, 0.075f, 0.255f, 0.17f, 38f, 687.5f, 0f, "RibSick" },
            new object[] { "leaf", "Leaf", "", 0f, 0.02f, 0f, 0.075f, 0.21f, 0.14f, 38f, 825f, 0f, "LeafSick" },
            new object[] { "leafRib", "Rib", "", 0f, 0.02f, 0f, 0.075f, 0.21f, 0.14f, 38f, 825f, 0f, "RibSick" },
        };
    }
}
