// <auto-generated> by tools/modelkit. Edit the model script and regenerate; do not edit by hand. </auto-generated>
namespace CigarSmoking
{
    internal static class M_plant_meadow_growing_sick
    {
        internal const float Scale = 1f;
        // name, shape, parent group (or ""), x, y, z, scale x, y, z, euler x, y, z, material
        internal static readonly object[][] Parts =
        {
            new object[] { "stalk", "Cylinder", "", 0f, 0.25f, 0f, 0.024f, 0.25f, 0.024f, 0f, 0f, 0f, "Stalk" },
            new object[] { "leaf", "Leaf", "", 0f, 0.05f, 0f, 0.1526f, 0.477f, 0.318f, 34f, 0f, 0f, "LeafSick" },
            new object[] { "leafRib", "Rib", "", 0f, 0.05f, 0f, 0.1526f, 0.477f, 0.318f, 34f, 0f, 0f, "RibSick" },
            new object[] { "leaf", "Leaf", "", 0f, 0.087f, 0f, 0.1594f, 0.498f, 0.332f, 32f, 137.5f, 0f, "LeafSick" },
            new object[] { "leafRib", "Rib", "", 0f, 0.087f, 0f, 0.1594f, 0.498f, 0.332f, 32f, 137.5f, 0f, "RibSick" },
            new object[] { "leaf", "Leaf", "", 0f, 0.124f, 0f, 0.1661f, 0.519f, 0.346f, 30f, 275f, 0f, "LeafSick" },
            new object[] { "leafRib", "Rib", "", 0f, 0.124f, 0f, 0.1661f, 0.519f, 0.346f, 30f, 275f, 0f, "RibSick" },
            new object[] { "leaf", "Leaf", "", 0f, 0.161f, 0f, 0.1728f, 0.54f, 0.36f, 28f, 412.5f, 0f, "LeafSick" },
            new object[] { "leafRib", "Rib", "", 0f, 0.161f, 0f, 0.1728f, 0.54f, 0.36f, 28f, 412.5f, 0f, "RibSick" },
            new object[] { "leaf", "Leaf", "", 0f, 0.198f, 0f, 0.1661f, 0.519f, 0.346f, 26f, 550f, 0f, "LeafSick" },
            new object[] { "leafRib", "Rib", "", 0f, 0.198f, 0f, 0.1661f, 0.519f, 0.346f, 26f, 550f, 0f, "RibSick" },
            new object[] { "leaf", "Leaf", "", 0f, 0.235f, 0f, 0.1594f, 0.498f, 0.332f, 24f, 687.5f, 0f, "LeafSick" },
            new object[] { "leafRib", "Rib", "", 0f, 0.235f, 0f, 0.1594f, 0.498f, 0.332f, 24f, 687.5f, 0f, "RibSick" },
            new object[] { "leaf", "Leaf", "", 0f, 0.272f, 0f, 0.1526f, 0.477f, 0.318f, 22f, 825f, 0f, "LeafSick" },
            new object[] { "leafRib", "Rib", "", 0f, 0.272f, 0f, 0.1526f, 0.477f, 0.318f, 22f, 825f, 0f, "RibSick" },
            new object[] { "leaf", "Leaf", "", 0f, 0.309f, 0f, 0.1459f, 0.456f, 0.304f, 20f, 962.5f, 0f, "LeafSick" },
            new object[] { "leafRib", "Rib", "", 0f, 0.309f, 0f, 0.1459f, 0.456f, 0.304f, 20f, 962.5f, 0f, "RibSick" },
            new object[] { "leaf", "Leaf", "", 0f, 0.346f, 0f, 0.1392f, 0.435f, 0.29f, 18f, 1100f, 0f, "LeafSick" },
            new object[] { "leafRib", "Rib", "", 0f, 0.346f, 0f, 0.1392f, 0.435f, 0.29f, 18f, 1100f, 0f, "RibSick" },
            new object[] { "leaf", "Leaf", "", 0f, 0.383f, 0f, 0.1325f, 0.414f, 0.276f, 16f, 1237.5f, 0f, "LeafSick" },
            new object[] { "leafRib", "Rib", "", 0f, 0.383f, 0f, 0.1325f, 0.414f, 0.276f, 16f, 1237.5f, 0f, "RibSick" },
            new object[] { "leaf", "Leaf", "", 0f, 0.42f, 0f, 0.1258f, 0.393f, 0.262f, 14f, 1375f, 0f, "LeafSick" },
            new object[] { "leafRib", "Rib", "", 0f, 0.42f, 0f, 0.1258f, 0.393f, 0.262f, 14f, 1375f, 0f, "RibSick" },
        };
    }
}
