// <auto-generated> by tools/modelkit. Edit the model script and regenerate; do not edit by hand. </auto-generated>
namespace CigarSmoking
{
    internal static class M_plant_forest_growing
    {
        internal const float Scale = 1f;
        // name, shape, parent group (or ""), x, y, z, scale x, y, z, euler x, y, z, material
        internal static readonly object[][] Parts =
        {
            new object[] { "stalk", "Cylinder", "", 0f, 0.25f, 0f, 0.024f, 0.25f, 0.024f, 0f, 0f, 0f, "Stalk" },
            new object[] { "leaf", "Leaf", "", 0f, 0.05f, 0f, 0.1168f, 0.4611f, 0.3074f, 34f, 0f, 0f, "LeafB_forest" },
            new object[] { "leafRib", "Rib", "", 0f, 0.05f, 0f, 0.1168f, 0.4611f, 0.3074f, 34f, 0f, 0f, "Rib_forest" },
            new object[] { "leaf", "Leaf", "", 0f, 0.087f, 0f, 0.122f, 0.4814f, 0.3209f, 32f, 137.5f, 0f, "Leaf_forest" },
            new object[] { "leafRib", "Rib", "", 0f, 0.087f, 0f, 0.122f, 0.4814f, 0.3209f, 32f, 137.5f, 0f, "Rib_forest" },
            new object[] { "leaf", "Leaf", "", 0f, 0.124f, 0f, 0.1271f, 0.5017f, 0.3345f, 30f, 275f, 0f, "LeafB_forest" },
            new object[] { "leafRib", "Rib", "", 0f, 0.124f, 0f, 0.1271f, 0.5017f, 0.3345f, 30f, 275f, 0f, "Rib_forest" },
            new object[] { "leaf", "Leaf", "", 0f, 0.161f, 0f, 0.1322f, 0.522f, 0.348f, 28f, 412.5f, 0f, "Leaf_forest" },
            new object[] { "leafRib", "Rib", "", 0f, 0.161f, 0f, 0.1322f, 0.522f, 0.348f, 28f, 412.5f, 0f, "Rib_forest" },
            new object[] { "leaf", "Leaf", "", 0f, 0.198f, 0f, 0.1271f, 0.5017f, 0.3345f, 26f, 550f, 0f, "LeafB_forest" },
            new object[] { "leafRib", "Rib", "", 0f, 0.198f, 0f, 0.1271f, 0.5017f, 0.3345f, 26f, 550f, 0f, "Rib_forest" },
            new object[] { "leaf", "Leaf", "", 0f, 0.235f, 0f, 0.122f, 0.4814f, 0.3209f, 24f, 687.5f, 0f, "Leaf_forest" },
            new object[] { "leafRib", "Rib", "", 0f, 0.235f, 0f, 0.122f, 0.4814f, 0.3209f, 24f, 687.5f, 0f, "Rib_forest" },
            new object[] { "leaf", "Leaf", "", 0f, 0.272f, 0f, 0.1168f, 0.4611f, 0.3074f, 22f, 825f, 0f, "LeafB_forest" },
            new object[] { "leafRib", "Rib", "", 0f, 0.272f, 0f, 0.1168f, 0.4611f, 0.3074f, 22f, 825f, 0f, "Rib_forest" },
            new object[] { "leaf", "Leaf", "", 0f, 0.309f, 0f, 0.1117f, 0.4408f, 0.2939f, 20f, 962.5f, 0f, "Leaf_forest" },
            new object[] { "leafRib", "Rib", "", 0f, 0.309f, 0f, 0.1117f, 0.4408f, 0.2939f, 20f, 962.5f, 0f, "Rib_forest" },
            new object[] { "leaf", "Leaf", "", 0f, 0.346f, 0f, 0.1065f, 0.4205f, 0.2803f, 18f, 1100f, 0f, "LeafB_forest" },
            new object[] { "leafRib", "Rib", "", 0f, 0.346f, 0f, 0.1065f, 0.4205f, 0.2803f, 18f, 1100f, 0f, "Rib_forest" },
            new object[] { "leaf", "Leaf", "", 0f, 0.383f, 0f, 0.1014f, 0.4002f, 0.2668f, 16f, 1237.5f, 0f, "Leaf_forest" },
            new object[] { "leafRib", "Rib", "", 0f, 0.383f, 0f, 0.1014f, 0.4002f, 0.2668f, 16f, 1237.5f, 0f, "Rib_forest" },
            new object[] { "leaf", "Leaf", "", 0f, 0.42f, 0f, 0.0962f, 0.3799f, 0.2533f, 14f, 1375f, 0f, "LeafB_forest" },
            new object[] { "leafRib", "Rib", "", 0f, 0.42f, 0f, 0.0962f, 0.3799f, 0.2533f, 14f, 1375f, 0f, "Rib_forest" },
        };
    }
}
