// <auto-generated> by tools/modelkit. Edit the model script and regenerate; do not edit by hand. </auto-generated>
namespace CigarSmoking
{
    internal static class M_seeds_meadow
    {
        internal const float Scale = 1f;
        // name, shape, parent group (or ""), x, y, z, scale x, y, z, euler x, y, z, material
        internal static readonly object[][] Parts =
        {
            new object[] { "pouch", "Sphere", "", 0f, 0.035f, 0f, 0.11f, 0.085f, 0.09f, 0f, 0f, 0f, "Twine" },
            new object[] { "pouchTop", "Sphere", "", 0f, 0.085f, 0f, 0.05f, 0.035f, 0.05f, 0f, 0f, 0f, "Twine" },
            new object[] { "ribbon", "Cylinder", "", 0f, 0.072f, 0f, 0.056f, 0.008f, 0.056f, 0f, 0f, 0f, "Flower_meadow" },
            new object[] { "bow", "Cube", "", 0.012f, 0.09f, 0f, 0.03f, 0.012f, 0.012f, 0f, 0f, 0f, "Flower_meadow" },
            new object[] { "seed", "Sphere", "", 0.0775f, 0.0127f, -0.0787f, 0.011f, 0.007f, 0.011f, 0f, 0f, 0f, "Seed" },
            new object[] { "seed", "Sphere", "", 0.0164f, 0.0132f, -0.0167f, 0.011f, 0.007f, 0.011f, 0f, 0f, 0f, "Seed" },
            new object[] { "seed", "Sphere", "", 0.0402f, 0.0128f, -0.067f, 0.011f, 0.007f, 0.011f, 0f, 0f, 0f, "Seed" },
            new object[] { "seed", "Sphere", "", 0.0123f, 0.0097f, -0.009f, 0.011f, 0.007f, 0.011f, 0f, 0f, 0f, "Seed" },
            new object[] { "seed", "Sphere", "", -0.0126f, 0.011f, -0.0378f, 0.011f, 0.007f, 0.011f, 0f, 0f, 0f, "Seed" },
            new object[] { "seed", "Sphere", "", 0.0872f, 0.0128f, -0.0513f, 0.011f, 0.007f, 0.011f, 0f, 0f, 0f, "Seed" },
            new object[] { "seed", "Sphere", "", 0.0893f, 0.0093f, -0.0533f, 0.011f, 0.007f, 0.011f, 0f, 0f, 0f, "Seed" },
            new object[] { "seed", "Sphere", "", -0.0004f, 0.0083f, -0.0708f, 0.011f, 0.007f, 0.011f, 0f, 0f, 0f, "Seed" },
            new object[] { "seed", "Sphere", "", 0.0007f, 0.0108f, -0.0522f, 0.011f, 0.007f, 0.011f, 0f, 0f, 0f, "Seed" },
            new object[] { "seed", "Sphere", "", -0.0167f, 0.0111f, -0.0894f, 0.011f, 0.007f, 0.011f, 0f, 0f, 0f, "Seed" },
            new object[] { "seed", "Sphere", "", 0.0309f, 0.0081f, -0.0058f, 0.011f, 0.007f, 0.011f, 0f, 0f, 0f, "Seed" },
            new object[] { "seed", "Sphere", "", 0.0151f, 0.0092f, -0.0813f, 0.011f, 0.007f, 0.011f, 0f, 0f, 0f, "Seed" },
            new object[] { "seed", "Sphere", "", 0.0804f, 0.013f, -0.0491f, 0.011f, 0.007f, 0.011f, 0f, 0f, 0f, "Seed" },
            new object[] { "seed", "Sphere", "", 0.0256f, 0.0133f, -0.0185f, 0.011f, 0.007f, 0.011f, 0f, 0f, 0f, "Seed" },
            new object[] { "seed", "Sphere", "", 0.0619f, 0.0118f, -0.0865f, 0.011f, 0.007f, 0.011f, 0f, 0f, 0f, "Seed" },
            new object[] { "seed", "Sphere", "", 0.0829f, 0.0112f, -0.0226f, 0.011f, 0.007f, 0.011f, 0f, 0f, 0f, "Seed" },
            new object[] { "seed", "Sphere", "", 0.0684f, 0.0102f, -0.0822f, 0.011f, 0.007f, 0.011f, 0f, 0f, 0f, "Seed" },
            new object[] { "seed", "Sphere", "", 0.0847f, 0.0103f, -0.0329f, 0.011f, 0.007f, 0.011f, 0f, 0f, 0f, "Seed" },
            new object[] { "seed", "Sphere", "", 0.0584f, 0.0129f, -0.0186f, 0.011f, 0.007f, 0.011f, 0f, 0f, 0f, "Seed" },
            new object[] { "seed", "Sphere", "", 0.0803f, 0.0115f, -0.0554f, 0.011f, 0.007f, 0.011f, 0f, 0f, 0f, "Seed" },
            new object[] { "seed", "Sphere", "", -0.0081f, 0.0121f, -0.0859f, 0.011f, 0.007f, 0.011f, 0f, 0f, 0f, "Seed" },
            new object[] { "seed", "Sphere", "", -0.0067f, 0.0094f, -0.0384f, 0.011f, 0.007f, 0.011f, 0f, 0f, 0f, "Seed" },
            new object[] { "seed", "Sphere", "", 0.0725f, 0.0138f, -0.0264f, 0.011f, 0.007f, 0.011f, 0f, 0f, 0f, "Seed" },
            new object[] { "seed", "Sphere", "", 0.0096f, 0.0098f, -0.0805f, 0.011f, 0.007f, 0.011f, 0f, 0f, 0f, "Seed" },
            new object[] { "seed", "Sphere", "", -0.005f, 0.0088f, -0.0955f, 0.011f, 0.007f, 0.011f, 0f, 0f, 0f, "Seed" },
            new object[] { "seed", "Sphere", "", 0.0921f, 0.0134f, -0.0679f, 0.011f, 0.007f, 0.011f, 0f, 0f, 0f, "Seed" },
        };
    }
}
