// <auto-generated> by tools/modelkit. Edit the model script and regenerate; do not edit by hand. </auto-generated>
namespace CigarSmoking
{
    internal static class M_table
    {
        internal const float Scale = 1f;
        // name, shape, parent group (or ""), x, y, z, scale x, y, z, euler x, y, z, material
        internal static readonly object[][] Parts =
        {
            new object[] { "leg", "Cube", "", -0.58f, 0.42f, -0.28f, 0.09f, 0.84f, 0.09f, 0f, 0f, 0f, "CedarDark" },
            new object[] { "leg", "Cube", "", -0.58f, 0.42f, 0.28f, 0.09f, 0.84f, 0.09f, 0f, 0f, 0f, "CedarDark" },
            new object[] { "leg", "Cube", "", 0.58f, 0.42f, -0.28f, 0.09f, 0.84f, 0.09f, 0f, 0f, 0f, "CedarDark" },
            new object[] { "leg", "Cube", "", 0.58f, 0.42f, 0.28f, 0.09f, 0.84f, 0.09f, 0f, 0f, 0f, "CedarDark" },
            new object[] { "topBoard", "Cube", "", 0f, 0.875f, -0.28f, 1.34f, 0.05f, 0.132f, 0f, 0f, 0f, "Cedar" },
            new object[] { "topBoard", "Cube", "", 0f, 0.875f, -0.14f, 1.34f, 0.05f, 0.132f, 0f, 0f, 0f, "Cedar" },
            new object[] { "topBoard", "Cube", "", 0f, 0.875f, 0f, 1.34f, 0.05f, 0.132f, 0f, 0f, 0f, "Cedar" },
            new object[] { "topBoard", "Cube", "", 0f, 0.875f, 0.14f, 1.34f, 0.05f, 0.132f, 0f, 0f, 0f, "Cedar" },
            new object[] { "topBoard", "Cube", "", 0f, 0.875f, 0.28f, 1.34f, 0.05f, 0.132f, 0f, 0f, 0f, "Cedar" },
            new object[] { "apron", "Cube", "", 0f, 0.8f, -0.28f, 1.18f, 0.08f, 0.04f, 0f, 0f, 0f, "CedarDark" },
            new object[] { "apron", "Cube", "", 0f, 0.8f, 0.28f, 1.18f, 0.08f, 0.04f, 0f, 0f, 0f, "CedarDark" },
            new object[] { "drawer", "Cube", "", 0.25f, 0.785f, -0.305f, 0.5f, 0.1f, 0.02f, 0f, 0f, 0f, "Cedar" },
            new object[] { "knob", "Sphere", "", 0.25f, 0.785f, -0.325f, 0.035f, 0.035f, 0.03f, 0f, 0f, 0f, "Brass" },
            new object[] { "shelf", "Cube", "", 0f, 0.22f, 0f, 1.2f, 0.035f, 0.6f, 0f, 0f, 0f, "Planks" },
            new object[] { "leaf", "Leaf", "", -0.32f, 0.26f, -0.08f, 0.102f, 0.6075f, 0.3f, -16f, -57.5f, 0f, "LeafAged" },
            new object[] { "leafRib", "Rib", "", -0.32f, 0.26f, -0.08f, 0.102f, 0.6075f, 0.3f, -16f, -57.5f, 0f, "LeafAgedRib" },
            new object[] { "leaf", "Leaf", "", -0.32f, 0.266f, -0.08f, 0.102f, 0.6075f, 0.3f, -12f, -33.75f, 0f, "LeafAged" },
            new object[] { "leafRib", "Rib", "", -0.32f, 0.266f, -0.08f, 0.102f, 0.6075f, 0.3f, -12f, -33.75f, 0f, "LeafAgedRib" },
            new object[] { "leaf", "Leaf", "", -0.32f, 0.272f, -0.08f, 0.102f, 0.6075f, 0.3f, -8f, -10f, 0f, "LeafAged" },
            new object[] { "leafRib", "Rib", "", -0.32f, 0.272f, -0.08f, 0.102f, 0.6075f, 0.3f, -8f, -10f, 0f, "LeafAgedRib" },
            new object[] { "leaf", "Leaf", "", -0.32f, 0.26f, -0.08f, 0.102f, 0.6075f, 0.3f, -16f, 13.75f, 0f, "LeafAged" },
            new object[] { "leafRib", "Rib", "", -0.32f, 0.26f, -0.08f, 0.102f, 0.6075f, 0.3f, -16f, 13.75f, 0f, "LeafAgedRib" },
            new object[] { "leaf", "Leaf", "", -0.32f, 0.266f, -0.08f, 0.102f, 0.6075f, 0.3f, -12f, 37.5f, 0f, "LeafAged" },
            new object[] { "leafRib", "Rib", "", -0.32f, 0.266f, -0.08f, 0.102f, 0.6075f, 0.3f, -12f, 37.5f, 0f, "LeafAgedRib" },
            new object[] { "twine", "Cylinder", "", -0.3243f, 0.272f, -0.0554f, 0.05f, 0.022f, 0.05f, 90f, -10f, 0f, "Twine" },
            new object[] { "jar", "Cylinder", "", 0.3f, 0.3f, 0f, 0.2f, 0.065f, 0.2f, 0f, 0f, 0f, "Iron" },
            new object[] { "jarLid", "Cylinder", "", 0.3f, 0.375f, 0f, 0.21f, 0.012f, 0.21f, 0f, 0f, 0f, "Dark" },
            new object[] { "mat", "Cube", "", -0.12f, 0.908f, -0.02f, 0.5f, 0.016f, 0.36f, 0f, 0f, 0f, "Felt" },
            new object[] { "matEdge", "Cube", "", -0.12f, 0.918f, -0.2f, 0.5f, 0.012f, 0.02f, 0f, 0f, 0f, "Twine" },
            new object[] { "leaf", "Leaf", "", -0.3f, 0.925f, 0f, 0.1288f, 0.42f, 0.28f, -16f, -33f, 0f, "LeafGreen" },
            new object[] { "leafRib", "Rib", "", -0.3f, 0.925f, 0f, 0.1288f, 0.42f, 0.28f, -16f, -33f, 0f, "LeafGreenRib" },
            new object[] { "leaf", "Leaf", "", -0.3f, 0.931f, 0f, 0.1288f, 0.42f, 0.28f, -12f, -16.3333f, 0f, "LeafGreen" },
            new object[] { "leafRib", "Rib", "", -0.3f, 0.931f, 0f, 0.1288f, 0.42f, 0.28f, -12f, -16.3333f, 0f, "LeafGreenRib" },
            new object[] { "leaf", "Leaf", "", -0.3f, 0.937f, 0f, 0.1288f, 0.42f, 0.28f, -8f, 0.3333f, 0f, "LeafGreen" },
            new object[] { "leafRib", "Rib", "", -0.3f, 0.937f, 0f, 0.1288f, 0.42f, 0.28f, -8f, 0.3333f, 0f, "LeafGreenRib" },
            new object[] { "leaf", "Leaf", "", -0.3f, 0.925f, 0f, 0.1288f, 0.42f, 0.28f, -16f, 17f, 0f, "LeafGreen" },
            new object[] { "leafRib", "Rib", "", -0.3f, 0.925f, 0f, 0.1288f, 0.42f, 0.28f, -16f, 17f, 0f, "LeafGreenRib" },
            new object[] { "twine", "Cylinder", "", -0.3035f, 0.937f, 0.0248f, 0.05f, 0.022f, 0.05f, 90f, -8f, 0f, "Twine" },
            new object[] { "board", "Cube", "", 0.36f, 0.912f, 0f, 0.34f, 0.024f, 0.46f, 0f, 0f, 0f, "Planks" },
            new object[] { "blade", "Cube", "", 0.36f, 0.935f, -0.12f, 0.2f, 0.012f, 0.045f, 0f, 8f, 0f, "Iron" },
            new object[] { "bladeHandle", "Cube", "", 0.48f, 0.94f, -0.13f, 0.08f, 0.025f, 0.035f, 0f, 8f, 0f, "Leather" },
            new object[] { "cigar", "Cylinder", "", -0.12f, 0.945f, 0.2f, 0.026f, 0.09f, 0.026f, 0f, 0f, 90f, "Body_connecticut" },
            new object[] { "cigarBand", "Cylinder", "", -0.09f, 0.945f, 0.2f, 0.029f, 0.012f, 0.029f, 0f, 0f, 90f, "Band_connecticut" },
            new object[] { "cigar", "Cylinder", "", -0.1f, 0.965f, 0.2f, 0.026f, 0.09f, 0.026f, 0f, 4f, 90f, "Body_connecticut" },
            new object[] { "cigarBand", "Cylinder", "", -0.07f, 0.965f, 0.2f, 0.029f, 0.012f, 0.029f, 0f, 4f, 90f, "Band_connecticut" },
            new object[] { "cigar", "Cylinder", "", -0.08f, 0.985f, 0.2f, 0.026f, 0.09f, 0.026f, 0f, 8f, 90f, "Body_connecticut" },
            new object[] { "cigarBand", "Cylinder", "", -0.05f, 0.985f, 0.2f, 0.029f, 0.012f, 0.029f, 0f, 8f, 90f, "Band_connecticut" },
        };
    }
}
