using System.Collections.Generic;
using BepInEx;
using BepInEx.Configuration;
using HarmonyLib;
using UnityEngine;

namespace BirdTrap
{
    /// <summary>
    /// A buildable bird trap: a slatted box with a drop-door propped up by a stick tied to the bait pedal. Bait it with berries or seeds
    /// and leave it under the open sky; in a while a bird hops in for the bait, the door drops, and the next time you come by you pluck
    /// it for feathers and let it go.
    ///
    /// Split across files: Plugin.cs (setup, registering the piece), ModelData.cs (the look, generated by tools/modelkit/birdtrap.py),
    /// ModelBuilder.cs and Look.cs (turning it into game objects), Icon.cs (the build-menu picture), Trap.cs (the piece: bait, catch, pluck).
    /// </summary>
    [BepInPlugin(Guid, Name, Version)]
    public class Plugin : BaseUnityPlugin
    {
        public const string Guid = "com.dhack.birdtrap";
        public const string Name = "BirdTrap";
        public const string Version = "1.0.0";
        public const string PiecePrefab = "piece_birdtrap";

        internal static ConfigEntry<float> MinMinutes, MaxMinutes;
        internal static ConfigEntry<int> MinFeathers, MaxFeathers, MaxBait;
        internal static ConfigEntry<bool> NeedsSky, RestsAtNight;

        private static GameObject _holder, _prefab;
        internal static EffectList DoorShut, DoorOpen;
        private Harmony _harmony;

        private void Awake()
        {
            // These decide when birds come, so they count on the game that owns the trap (usually the nearest player's).
            MinMinutes = Config.Bind("Catching", "MinutesMin", 8f, new ConfigDescription("Shortest wait (real minutes, in game time) from baiting to a bird.", new AcceptableValueRange<float>(0.5f, 120f)));
            MaxMinutes = Config.Bind("Catching", "MinutesMax", 14f, new ConfigDescription("Longest wait (real minutes, in game time) from baiting to a bird.", new AcceptableValueRange<float>(0.5f, 240f)));
            MaxBait = Config.Bind("Catching", "BaitHeld", 5, new ConfigDescription("How many pieces of bait a trap holds (each bird eats one).", new AcceptableValueRange<int>(1, 20)));
            NeedsSky = Config.Bind("Catching", "NeedsOpenSky", true, "Birds only come to a trap with open sky above it (not under a roof).");
            RestsAtNight = Config.Bind("Catching", "BirdsRoostAtNight", true, "No birds come at night: one due then comes in the morning.");
            MinFeathers = Config.Bind("Plucking", "FeathersMin", 2, new ConfigDescription("Fewest feathers a bird gives.", new AcceptableValueRange<int>(1, 20)));
            MaxFeathers = Config.Bind("Plucking", "FeathersMax", 3, new ConfigDescription("Most feathers a bird gives.", new AcceptableValueRange<int>(1, 20)));

            _harmony = new Harmony(Guid);
            _harmony.PatchAll();
            if (ZNetScene.instance != null) Register(ZNetScene.instance); // hot reload while in a world
            Logger.LogInfo($"{Name} {Version} loaded");
        }

        // ---- Claude Tools (if installed): a "traps" command reporting every trap loaded ----
        private BaseUnityPlugin _claudeTools;
        private float _nextClaudeCheck;

        private void Update()
        {
            if (Time.unscaledTime < _nextClaudeCheck) return;
            _nextClaudeCheck = Time.unscaledTime + 5f;
            BaseUnityPlugin found = System.Linq.Enumerable.FirstOrDefault(Resources.FindObjectsOfTypeAll<BaseUnityPlugin>(),
                p => p != null && p.gameObject.scene.IsValid() && MetadataHelper.GetMetadata(p)?.GUID == "com.dhack.claudetools");
            if (found == _claudeTools) return;
            _claudeTools = found;
            if (found == null) return;
            try
            {
                var register = found.GetType().GetMethod("RegisterCommand", System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Static);
                System.Func<string[], System.Action<Newtonsoft.Json.Linq.JObject>, System.Action<string>, System.Collections.IEnumerator> traps = (a, output, error) =>
                {
                    Vector3 me = Player.m_localPlayer != null ? Player.m_localPlayer.transform.position : Vector3.zero;
                    var list = new Newtonsoft.Json.Linq.JArray();
                    foreach (TrapPiece t in System.Linq.Enumerable.OrderBy(TrapPiece.All, x => Vector3.Distance(x.transform.position, me))) if (t != null) list.Add(t.Report(me));
                    output(new Newtonsoft.Json.Linq.JObject { ["traps"] = list, ["day"] = EnvMan.instance != null ? EnvMan.instance.GetDay() : 0, ["night"] = EnvMan.instance != null && EnvMan.IsNight() });
                    return null;
                };
                register?.Invoke(null, new object[] { Name, "traps", "traps: every bird trap loaded: bait, bird, minutes to the next bird, open sky, owner", traps });
            }
            catch (System.Exception e) { Logger.LogWarning("Could not add the traps command to Claude Tools: " + e.Message); }
        }

        private void OnDestroy()
        {
            try { _claudeTools?.GetType().GetMethod("UnregisterAll", System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Static)?.Invoke(null, new object[] { Name }); } catch { }
            _harmony?.UnpatchSelf();
            Unregister();
        }

        internal static void Register(ZNetScene scene)
        {
            GameObject source = scene.GetPrefab("piece_chest_wood");
            GameObject hammer = scene.GetPrefab("Hammer"); // items are in the scene too, and ObjectDB may not be awake yet
            GameObject bench = scene.GetPrefab("piece_workbench");
            if (source == null || hammer == null) { Debug.LogWarning(Name + ": chest or hammer prefab not found"); return; }

            if (_prefab == null)
            {
                _holder = new GameObject(Name + "Prefabs");
                _holder.SetActive(false); // keeps the copy from waking up as a real object
                Object.DontDestroyOnLoad(_holder);
                Look.Harvest(scene, source.GetComponentInChildren<Renderer>(true).sharedMaterial);
                Container chest = source.GetComponent<Container>();
                DoorShut = chest != null ? chest.m_closeEffects : null; // the chest lid's thunk for the door dropping
                DoorOpen = chest != null ? chest.m_openEffects : null;
                _prefab = Make(source, bench != null ? bench.GetComponent<CraftingStation>() : null);
            }

            var named = (Dictionary<int, GameObject>)AccessTools.Field(typeof(ZNetScene), "m_namedPrefabs").GetValue(scene);
            PieceTable table = hammer.GetComponent<ItemDrop>().m_itemData.m_shared.m_buildPieces;
            if (!scene.m_prefabs.Contains(_prefab)) scene.m_prefabs.Add(_prefab);
            named[_prefab.name.GetStableHashCode()] = _prefab; // lets it be placed and loaded from saves
            if (!table.m_pieces.Contains(_prefab)) table.m_pieces.Add(_prefab);
            RefreshPlaced();
        }

        /// <summary>
        /// After a hot reload the traps already standing keep the old copy's script until their area reloads. Swap it for this one (the
        /// trap's state is all on the trap, so nothing is lost).
        /// </summary>
        private static void RefreshPlaced()
        {
            int n = 0;
            foreach (ZNetView view in Object.FindObjectsByType<ZNetView>(FindObjectsSortMode.None))
            {
                if (view == null || view.GetZDO() == null || !view.gameObject.name.StartsWith(PiecePrefab)) continue;
                foreach (MonoBehaviour old in view.GetComponents<MonoBehaviour>())
                    if (old != null && old.GetType().Name == nameof(TrapPiece) && old.GetType() != typeof(TrapPiece)) Object.DestroyImmediate(old);
                if (view.GetComponent<TrapPiece>() == null) { view.gameObject.AddComponent<TrapPiece>(); n++; }
            }
            if (n > 0) Debug.Log($"[{Name}] refreshed {n} trap(s) already built");
        }

        private static GameObject Make(GameObject source, CraftingStation workbench)
        {
            GameObject go = Object.Instantiate(source, _holder.transform);
            go.name = PiecePrefab;
            Container container = go.GetComponent<Container>();
            if (container != null) Object.DestroyImmediate(container); // it is not storage

            int layer = LayerMask.NameToLayer("piece");
            if (layer < 0) layer = go.layer;
            foreach (Renderer r in go.GetComponentsInChildren<Renderer>(true)) r.enabled = false; // hide the chest
            foreach (Collider c in go.GetComponentsInChildren<Collider>(true)) Object.DestroyImmediate(c); // and its hitbox
            var hit = new GameObject("Hitbox") { layer = layer };
            hit.transform.SetParent(go.transform, false);
            var box = hit.AddComponent<BoxCollider>();
            box.center = new Vector3(0f, 0.42f, 0f);
            box.size = new Vector3(0.92f, 0.84f, 0.66f);

            ModelBuilder.Build(go.transform, ModelData.Parts, go.layer);

            Piece piece = go.GetComponent<Piece>();
            piece.m_name = "Bird Trap";
            piece.m_description = "A slatted box with a drop-door on a prop stick. Bait it with berries or seeds and leave it under the open sky: in a while a bird hops in, the door drops, and you can pluck it for feathers.";
            piece.m_category = Piece.PieceCategory.Misc;
            piece.m_craftingStation = workbench;
            piece.m_resources = new[] { Req("Wood", 8), Req("LeatherScraps", 2) };
            piece.m_icon = Icon.Make(go);
            go.AddComponent<TrapPiece>();
            return go;
        }

        internal static void Unregister()
        {
            if (_prefab == null) return;
            if (ZNetScene.instance != null)
            {
                ZNetScene.instance.m_prefabs.Remove(_prefab);
                var named = (Dictionary<int, GameObject>)AccessTools.Field(typeof(ZNetScene), "m_namedPrefabs").GetValue(ZNetScene.instance);
                int hash = _prefab.name.GetStableHashCode();
                if (named.TryGetValue(hash, out GameObject current) && current == _prefab) named.Remove(hash); // only our own entry
            }
            GameObject hammer = ObjectDB.instance != null ? ObjectDB.instance.GetItemPrefab("Hammer") : null;
            if (hammer != null) hammer.GetComponent<ItemDrop>().m_itemData.m_shared.m_buildPieces.m_pieces.Remove(_prefab);
            _prefab = null;
            Object.Destroy(_holder);
            _holder = null;
            Look.Clear();
        }

        private static Piece.Requirement Req(string item, int amount)
        {
            GameObject go = ZNetScene.instance != null ? ZNetScene.instance.GetPrefab(item) : null;
            if (go == null && ObjectDB.instance != null) go = ObjectDB.instance.GetItemPrefab(item);
            return new Piece.Requirement { m_resItem = go != null ? go.GetComponent<ItemDrop>() : null, m_amount = amount, m_recover = true };
        }
    }

    [HarmonyPatch(typeof(ZNetScene), "Awake")]
    internal static class ZNetScene_Awake
    {
        private static void Postfix(ZNetScene __instance) => Plugin.Register(__instance);
    }

    // Whichever of ZNetScene and ObjectDB wakes second, the piece is registered before any saved one is loaded.
    [HarmonyPatch(typeof(ObjectDB), "Awake")]
    internal static class ObjectDB_Awake
    {
        private static void Postfix() { if (ZNetScene.instance != null) Plugin.Register(ZNetScene.instance); }
    }
}
