// <auto-generated> by tools/modelkit/build_cigars.py. Do not edit by hand. </auto-generated>
namespace CigarSmoking
{
    internal static class ModelIndex
    {
        internal static object[][] Parts(string name)
        {
            switch (name)
            {
                case "rack": return M_rack.Parts;
                case "barrel": return M_barrel.Parts;
                case "table": return M_table.Parts;
                case "humidor": return M_humidor.Parts;
                case "plant_meadow_seedling": return M_plant_meadow_seedling.Parts;
                case "plant_meadow_growing": return M_plant_meadow_growing.Parts;
                case "plant_meadow_mature": return M_plant_meadow_mature.Parts;
                case "plant_meadow_seedling_sick": return M_plant_meadow_seedling_sick.Parts;
                case "plant_meadow_growing_sick": return M_plant_meadow_growing_sick.Parts;
                case "leaf_meadow_fresh": return M_leaf_meadow_fresh.Parts;
                case "leaf_meadow_dried": return M_leaf_meadow_dried.Parts;
                case "leaf_meadow_aged": return M_leaf_meadow_aged.Parts;
                case "seeds_meadow": return M_seeds_meadow.Parts;
                case "plant_forest_seedling": return M_plant_forest_seedling.Parts;
                case "plant_forest_growing": return M_plant_forest_growing.Parts;
                case "plant_forest_mature": return M_plant_forest_mature.Parts;
                case "plant_forest_seedling_sick": return M_plant_forest_seedling_sick.Parts;
                case "plant_forest_growing_sick": return M_plant_forest_growing_sick.Parts;
                case "leaf_forest_fresh": return M_leaf_forest_fresh.Parts;
                case "leaf_forest_dried": return M_leaf_forest_dried.Parts;
                case "leaf_forest_aged": return M_leaf_forest_aged.Parts;
                case "seeds_forest": return M_seeds_forest.Parts;
                case "plant_plains_seedling": return M_plant_plains_seedling.Parts;
                case "plant_plains_growing": return M_plant_plains_growing.Parts;
                case "plant_plains_mature": return M_plant_plains_mature.Parts;
                case "plant_plains_seedling_sick": return M_plant_plains_seedling_sick.Parts;
                case "plant_plains_growing_sick": return M_plant_plains_growing_sick.Parts;
                case "leaf_plains_fresh": return M_leaf_plains_fresh.Parts;
                case "leaf_plains_dried": return M_leaf_plains_dried.Parts;
                case "leaf_plains_aged": return M_leaf_plains_aged.Parts;
                case "seeds_plains": return M_seeds_plains.Parts;
            }
            throw new System.ArgumentException("no model called " + name);
        }
    }
}
