using System.Collections.Generic;
using BepInEx;
using BepInEx.Configuration;
using HarmonyLib;
using UnityEngine;

namespace LedgerChest
{
    /// <summary>
    /// The Ledger Chest: a strongbox you build that is a chest of its own and, when you open it, shows everything in every chest around it
    /// in one list, with a search. Click an item to take it out of whichever chest holds it.
    ///
    /// Split across files: Plugin.cs (setup, registering the piece), ModelData.cs (the look, generated by tools/modelkit/ledgerchest.py),
    /// ModelBuilder.cs and Look.cs (turning it into game objects), Icon.cs (the build-menu picture), Stores.cs (finding the chests and
    /// taking from them), Ledger.cs (the list beside the chest).
    /// </summary>
    [BepInPlugin(Guid, Name, Version)]
    public class Plugin : BaseUnityPlugin
    {
        public const string Guid = "com.dhack.ledgerchest";
        public const string Name = "LedgerChest";
        public const string Version = "1.0.0";
        public const string PiecePrefab = "piece_ledgerchest";

        internal static Plugin Instance;
        internal static ConfigEntry<float> Radius, Scale;

        private static GameObject _holder, _prefab;
        private Harmony _harmony;
        internal readonly Ledger Window = new Ledger();

        private void Awake()
        {
            Instance = this;
            Radius = Config.Bind("Ledger", "Radius", 30f, new ConfigDescription("How far from the Ledger Chest (metres) the chests it lists can be.", new AcceptableValueRange<float>(5f, 60f)));
            Scale = Config.Bind("Ledger", "Scale", 1f, new ConfigDescription("Size of the list beside the chest.", new AcceptableValueRange<float>(0.6f, 2f)));
            _harmony = new Harmony(Guid);
            _harmony.PatchAll();
            if (ZNetScene.instance != null) Register(ZNetScene.instance); // hot reload while in a world
            Logger.LogInfo($"{Name} {Version} loaded");
        }

        private void OnDestroy()
        {
            try { _claudeTools?.GetType().GetMethod("UnregisterAll", System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Static)?.Invoke(null, new object[] { Name }); } catch { }
            Window.Close();
            Window.Destroy();
            if (Instance == this) Instance = null;
            _harmony?.UnpatchSelf();
            Unregister();
        }

        private void Update()
        {
            Window.Tick();
            ClaudeLink();
        }

        // ---- Claude Tools (if installed): a "ledgers" command reporting each Ledger Chest's state (for finding problems) ----
        private BaseUnityPlugin _claudeTools;
        private float _nextClaudeCheck;

        private void ClaudeLink()
        {
            if (Time.unscaledTime < _nextClaudeCheck) return;
            _nextClaudeCheck = Time.unscaledTime + 5f;
            BaseUnityPlugin found = System.Linq.Enumerable.FirstOrDefault(Resources.FindObjectsOfTypeAll<BaseUnityPlugin>(),
                pl => pl != null && pl.gameObject.scene.IsValid() && MetadataHelper.GetMetadata(pl)?.GUID == "com.dhack.claudetools");
            if (found == _claudeTools) return;
            _claudeTools = found;
            if (found == null) return;
            var register = found.GetType().GetMethod("RegisterCommand", System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Static);
            System.Func<string[], System.Action<Newtonsoft.Json.Linq.JObject>, System.Action<string>, System.Collections.IEnumerator> cmd = (a, output, error) =>
            {
                var list = new Newtonsoft.Json.Linq.JArray();
                foreach (Container c in Object.FindObjectsByType<Container>(FindObjectsInactive.Include, FindObjectsSortMode.None))
                {
                    if (c == null || !c.gameObject.name.StartsWith(PiecePrefab)) continue;
                    ZNetView v = c.GetComponent<ZNetView>();
                    var comps = new Newtonsoft.Json.Linq.JArray();
                    foreach (Component k in c.GetComponents<Component>()) comps.Add(k == null ? "(missing script)" : k.GetType().Name + (k is Behaviour b && !b.enabled ? " (off)" : ""));
                    var cols = new Newtonsoft.Json.Linq.JArray();
                    foreach (Collider col in c.GetComponentsInChildren<Collider>(true)) cols.Add($"{col.name} {LayerMask.LayerToName(col.gameObject.layer)} {(col.enabled && col.gameObject.activeInHierarchy ? "on" : "OFF")}");
                    list.Add(new Newtonsoft.Json.Linq.JObject
                    {
                        ["name"] = c.gameObject.name, ["active"] = c.gameObject.activeInHierarchy, ["position"] = c.transform.position.ToString("F1"),
                        ["nviewValid"] = v != null && v.IsValid(), ["owner"] = v != null && v.IsValid() ? v.GetZDO().GetOwner().ToString() : "-", ["mine"] = v != null && v.IsValid() && v.IsOwner(),
                        ["inUse"] = c.IsInUse(), ["components"] = comps, ["colliders"] = cols, ["isPrefabCopy"] = c.transform.parent != null && c.transform.parent.name.EndsWith("Prefabs"),
                    });
                }
                output(new Newtonsoft.Json.Linq.JObject { ["ledgers"] = list });
                return null;
            };
            register?.Invoke(null, new object[] { Name, "ledgers", "ledgers: every Ledger Chest object: active, its network view, owner, components, colliders", cmd });
            System.Func<string[], System.Action<Newtonsoft.Json.Linq.JObject>, System.Action<string>, System.Collections.IEnumerator> kinds = (a, output, error) =>
            {
                var by = new Newtonsoft.Json.Linq.JObject();
                if (ObjectDB.instance != null)
                    foreach (GameObject go in ObjectDB.instance.m_items)
                    {
                        ItemDrop d = go != null ? go.GetComponent<ItemDrop>() : null;
                        if (d == null) continue;
                        string k = Kinds.Of(d.m_itemData.m_shared);
                        if (by[k] == null) by[k] = new Newtonsoft.Json.Linq.JArray();
                        ((Newtonsoft.Json.Linq.JArray)by[k]).Add($"{d.m_itemData.m_shared.m_name} ({Localization.instance.Localize(d.m_itemData.m_shared.m_name)})");
                    }
                output(new Newtonsoft.Json.Linq.JObject { ["kinds"] = by });
                return null;
            };
            register?.Invoke(null, new object[] { Name, "ledgerkinds", "ledgerkinds: every item in the game under the ledger button it shows under", kinds });
        }
        private void OnGUI() => Window.Draw();

        /// <summary>A Ledger Chest (by its name: one built before a reload of this mod carries the old copy's marker).</summary>
        internal static bool IsLedger(Component c) => c != null && c.gameObject.name.StartsWith(PiecePrefab, System.StringComparison.Ordinal);

        internal static void Register(ZNetScene scene)
        {
            GameObject source = scene.GetPrefab("piece_chest_wood");
            GameObject hammer = scene.GetPrefab("Hammer"); // items are in the scene too, and ObjectDB may not be awake yet
            GameObject bench = scene.GetPrefab("piece_workbench");
            if (source == null || hammer == null) { Debug.LogWarning(Name + ": chest or hammer prefab not found"); return; }

            if (_prefab == null)
            {
                _holder = new GameObject(Name + "Prefabs");
                _holder.SetActive(false); // keeps the copy from waking up as a real object
                Object.DontDestroyOnLoad(_holder);
                Look.Harvest(scene, source.GetComponentInChildren<Renderer>(true).sharedMaterial);
                _prefab = Make(source, bench != null ? bench.GetComponent<CraftingStation>() : null);
            }

            var named = (Dictionary<int, GameObject>)AccessTools.Field(typeof(ZNetScene), "m_namedPrefabs").GetValue(scene);
            PieceTable table = hammer.GetComponent<ItemDrop>().m_itemData.m_shared.m_buildPieces;
            if (!scene.m_prefabs.Contains(_prefab)) scene.m_prefabs.Add(_prefab);
            named[_prefab.name.GetStableHashCode()] = _prefab; // lets it be placed and loaded from saves
            if (!table.m_pieces.Contains(_prefab)) table.m_pieces.Add(_prefab);
        }

        private static GameObject Make(GameObject source, CraftingStation workbench)
        {
            GameObject go = Object.Instantiate(source, _holder.transform);
            go.name = PiecePrefab;

            // It stays a chest (the game's own: opening, saving, multiplayer), a bigger one, with its own name.
            Container chest = go.GetComponent<Container>();
            chest.m_name = "Ledger Chest";
            chest.m_width = 6;
            chest.m_height = 3;

            int layer = LayerMask.NameToLayer("piece");
            if (layer < 0) layer = go.layer;
            foreach (Renderer r in go.GetComponentsInChildren<Renderer>(true)) r.enabled = false; // hide the wooden chest
            foreach (Collider c in go.GetComponentsInChildren<Collider>(true)) Object.DestroyImmediate(c); // and its hitbox
            var hit = new GameObject("Hitbox") { layer = layer };
            hit.transform.SetParent(go.transform, false);
            var box = hit.AddComponent<BoxCollider>();
            box.center = new Vector3(0f, 0.45f, 0f);
            box.size = new Vector3(1.38f, 0.9f, 0.82f);
            var top = hit.AddComponent<BoxCollider>(); // the stand and the book on the lid
            top.center = new Vector3(-0.12f, 0.98f, 0.05f);
            top.size = new Vector3(0.66f, 0.42f, 0.46f);

            ModelBuilder.Build(go.transform, ModelData.Parts, go.layer);

            Piece piece = go.GetComponent<Piece>();
            piece.m_name = "Ledger Chest";
            piece.m_description = "An iron-bound strongbox with the storehouse ledger on its lid. Open it to see everything in every chest around it, search it, and take what you need from whichever chest holds it.";
            piece.m_category = Piece.PieceCategory.Furniture;
            piece.m_craftingStation = workbench;
            piece.m_resources = new[] { Req("Wood", 10), Req("FineWood", 4), Req("LeatherScraps", 4), Req("Resin", 2) };
            piece.m_icon = Icon.Make(go);
            go.AddComponent<LedgerPiece>();
            return go;
        }

        internal static void Unregister()
        {
            if (_prefab == null) return;
            if (ZNetScene.instance != null)
            {
                ZNetScene.instance.m_prefabs.Remove(_prefab);
                var named = (Dictionary<int, GameObject>)AccessTools.Field(typeof(ZNetScene), "m_namedPrefabs").GetValue(ZNetScene.instance);
                int hash = _prefab.name.GetStableHashCode();
                if (named.TryGetValue(hash, out GameObject current) && current == _prefab) named.Remove(hash); // only our own entry
            }
            GameObject hammer = ObjectDB.instance != null ? ObjectDB.instance.GetItemPrefab("Hammer") : null;
            if (hammer != null) hammer.GetComponent<ItemDrop>().m_itemData.m_shared.m_buildPieces.m_pieces.Remove(_prefab);
            _prefab = null;
            Object.Destroy(_holder);
            _holder = null;
            Look.Clear();
        }

        private static Piece.Requirement Req(string item, int amount)
        {
            GameObject go = ZNetScene.instance != null ? ZNetScene.instance.GetPrefab(item) : null;
            if (go == null && ObjectDB.instance != null) go = ObjectDB.instance.GetItemPrefab(item);
            return new Piece.Requirement { m_resItem = go != null ? go.GetComponent<ItemDrop>() : null, m_amount = amount, m_recover = true };
        }
    }

    /// <summary>Marks a Ledger Chest (the list shows when one of these is open).</summary>
    public class LedgerPiece : MonoBehaviour { }

    // Opening a Ledger Chest asks its owner's game, as any chest. When that is a player without this mod (the nearest player owns what is
    // around them), nothing answers and it never opens: you take it over first (unless someone has it open). It keeps nothing, so that is safe.
    [HarmonyPatch(typeof(Container), nameof(Container.Interact))]
    internal static class Container_Interact_Ledger
    {
        private static void Prefix(Container __instance, bool hold)
        {
            if (hold || !Plugin.IsLedger(__instance)) return;
            ZNetView v = __instance.GetComponent<ZNetView>();
            if (v == null || !v.IsValid() || v.IsOwner() || v.GetZDO().GetInt(ZDOVars.s_inUse, 0) == 1) return;
            v.ClaimOwnership();
        }
    }

    [HarmonyPatch(typeof(ZNetScene), "Awake")]
    internal static class ZNetScene_Awake
    {
        private static void Postfix(ZNetScene __instance) => Plugin.Register(__instance);
    }

    // Whichever of ZNetScene and ObjectDB wakes second, the piece is registered before any saved one is loaded.
    [HarmonyPatch(typeof(ObjectDB), "Awake")]
    internal static class ObjectDB_Awake
    {
        private static void Postfix() { if (ZNetScene.instance != null) Plugin.Register(ZNetScene.instance); }
    }

    // While you type in the search: your character and the inventory's keys (Tab, E) do not react to the letters.
    [HarmonyPatch(typeof(Player), "TakeInput")]
    internal static class Player_TakeInput
    {
        private static void Postfix(Player __instance, ref bool __result) { if (__instance == Player.m_localPlayer && Plugin.Instance != null && Plugin.Instance.Window.Typing) __result = false; }
    }

    [HarmonyPatch(typeof(PlayerController), "TakeInput")]
    internal static class PlayerController_TakeInput
    {
        private static void Postfix(ref bool __result) { if (Plugin.Instance != null && Plugin.Instance.Window.Typing) __result = false; }
    }

    [HarmonyPatch(typeof(InventoryGui), "Update")]
    internal static class InventoryGui_Update
    {
        private static void Prefix()
        {
            if (Plugin.Instance == null || !Plugin.Instance.Window.Typing) return;
            ZInput.ResetButtonStatus("Use");        // E would close the chest
            ZInput.ResetButtonStatus("Inventory");  // and Tab the inventory
        }
    }
}
