using System.Collections.Generic;
using BepInEx;
using BepInEx.Configuration;
using HarmonyLib;
using UnityEngine;

namespace SlotMachine
{
    /// <summary>
    /// A buildable slot machine, Odin's Fortune. Build it at a forge (it costs real materials and a stack of coins for the house), then put
    /// coins in: three reels spin, and a win is spat out of the tray. Over time it gives back about 93% of what goes in.
    ///
    /// Split across files: Plugin.cs (setup, registering the piece), ModelData.cs (the look, generated by tools/modelkit),
    /// ModelBuilder.cs and Look.cs (turning it into game objects), Icon.cs (the build-menu picture), Payout.cs (the odds),
    /// Machine.cs (the piece: pulling, spinning, paying).
    /// </summary>
    [BepInPlugin(Guid, Name, Version)]
    public class Plugin : BaseUnityPlugin
    {
        public const string Guid = "com.dhack.slotmachine";
        public const string Name = "SlotMachine";
        public const string Version = "1.0.0";
        public const string PiecePrefab = "piece_slotmachine";

        internal static ConfigEntry<int> Bet, PayoutPercent;
        private static readonly int[] Bets = { 5, 10, 25, 50, 100 };

        private static GameObject _holder, _prefab;
        private Harmony _harmony;

        private void Awake()
        {
            Bet = Config.Bind("Play", "Bet", 10, new ConfigDescription("Coins per pull (change it at the machine with the alternate-use key + use).", new AcceptableValueList<int>(Bets)));
            PayoutPercent = Config.Bind("Play", "PayoutPercent", 100, new ConfigDescription("Scales every prize (100 = standard, which returns about 93% over time; 50 = half the prizes).", new AcceptableValueRange<int>(10, 300)));

            _harmony = new Harmony(Guid);
            _harmony.PatchAll();
            if (ZNetScene.instance != null) Register(ZNetScene.instance); // hot reload while in a world
            Logger.LogInfo($"{Name} {Version} loaded");
        }

        private void OnDestroy()
        {
            _harmony?.UnpatchSelf();
            Unregister();
        }

        internal static void NextBet()
        {
            int i = System.Array.IndexOf(Bets, Bet.Value);
            Bet.Value = Bets[(i + 1) % Bets.Length];
        }

        internal static void Register(ZNetScene scene)
        {
            if (ObjectDB.instance == null) return;
            GameObject source = scene.GetPrefab("piece_chest_wood");
            GameObject hammer = ObjectDB.instance.GetItemPrefab("Hammer");
            GameObject bench = scene.GetPrefab("piece_forge");
            if (source == null || hammer == null) { Debug.LogWarning(Name + ": chest or hammer prefab not found"); return; }

            if (_prefab == null)
            {
                _holder = new GameObject(Name + "Prefabs");
                _holder.SetActive(false); // keeps the copy from waking up as a real object
                Object.DontDestroyOnLoad(_holder);
                Look.Harvest(scene, source.GetComponentInChildren<Renderer>(true).sharedMaterial);
                _prefab = Make(source, bench != null ? bench.GetComponent<CraftingStation>() : null);
            }

            var named = (Dictionary<int, GameObject>)AccessTools.Field(typeof(ZNetScene), "m_namedPrefabs").GetValue(scene);
            PieceTable table = hammer.GetComponent<ItemDrop>().m_itemData.m_shared.m_buildPieces;
            if (!scene.m_prefabs.Contains(_prefab)) scene.m_prefabs.Add(_prefab);
            named[_prefab.name.GetStableHashCode()] = _prefab; // lets it be placed and loaded from saves
            if (!table.m_pieces.Contains(_prefab)) table.m_pieces.Add(_prefab);
        }

        private static GameObject Make(GameObject source, CraftingStation workbench)
        {
            GameObject go = Object.Instantiate(source, _holder.transform);
            go.name = PiecePrefab;
            Container container = go.GetComponent<Container>();
            if (container != null) Object.DestroyImmediate(container); // it is not storage

            int layer = LayerMask.NameToLayer("piece");
            if (layer < 0) layer = go.layer;
            foreach (Renderer r in go.GetComponentsInChildren<Renderer>(true)) r.enabled = false; // hide the chest
            foreach (Collider c in go.GetComponentsInChildren<Collider>(true)) Object.DestroyImmediate(c); // and its hitbox
            var hit = new GameObject("Hitbox") { layer = layer };
            hit.transform.SetParent(go.transform, false);
            var box = hit.AddComponent<BoxCollider>();
            box.center = new Vector3(0f, 1.13f, -0.02f);
            box.size = new Vector3(1.05f, 2.3f, 0.92f);

            ModelBuilder.Build(go.transform, ModelData.Parts, go.layer);

            Piece piece = go.GetComponent<Piece>();
            piece.m_name = "Odin's Fortune";
            piece.m_description = "A slot machine. Put coins in, pull the lever, and three reels spin. Three alike pay out, and the winnings come out of the tray.";
            piece.m_category = Piece.PieceCategory.Misc;
            piece.m_craftingStation = workbench;
            piece.m_resources = new[] { Req("FineWood", 15), Req("Iron", 10), Req("Bronze", 8), Req("Coins", 150) };
            piece.m_icon = Icon.Make(go);
            go.AddComponent<SlotMachinePiece>();
            return go;
        }

        internal static void Unregister()
        {
            if (_prefab == null) return;
            if (ZNetScene.instance != null)
            {
                ZNetScene.instance.m_prefabs.Remove(_prefab);
                ((Dictionary<int, GameObject>)AccessTools.Field(typeof(ZNetScene), "m_namedPrefabs").GetValue(ZNetScene.instance)).Remove(_prefab.name.GetStableHashCode());
            }
            GameObject hammer = ObjectDB.instance != null ? ObjectDB.instance.GetItemPrefab("Hammer") : null;
            if (hammer != null) hammer.GetComponent<ItemDrop>().m_itemData.m_shared.m_buildPieces.m_pieces.Remove(_prefab);
            _prefab = null;
            Object.Destroy(_holder);
            _holder = null;
            Look.Clear();
        }

        private static Piece.Requirement Req(string item, int amount)
        {
            GameObject go = ObjectDB.instance.GetItemPrefab(item);
            return new Piece.Requirement { m_resItem = go != null ? go.GetComponent<ItemDrop>() : null, m_amount = amount, m_recover = true };
        }
    }

    [HarmonyPatch(typeof(ZNetScene), "Awake")]
    internal static class ZNetScene_Awake
    {
        private static void Postfix(ZNetScene __instance) => Plugin.Register(__instance);
    }
}
