"""
Regenerates Quad's Cigars' C# models (mods/CigarSmoking/Models/*.cs, with ModelIndex.cs to look them up by name), the pictures of every
item and piece (mods/CigarSmoking/icons/*.png, embedded in the mod) and the cover. Run from this folder; it takes a few minutes.
"""
import os
import sys
from modelkit import render, icon
import cigars

root = os.path.join("..", "..", "mods", "CigarSmoking")
out = os.path.join(root, "Models")
icons = os.path.join(root, "icons")
os.makedirs(out, exist_ok=True)
os.makedirs(icons, exist_ok=True)

# name -> model (the same names the mod asks ModelIndex for)
MODELS = {"rack": cigars.rack(), "barrel": cigars.barrel(), "table": cigars.table(), "humidor": cigars.humidor()}
for s in cigars.STRAINS:
    for stage in ("seedling", "growing", "mature"):
        MODELS["plant_%s_%s" % (s, stage)] = cigars.plant(s, stage)
    for stage in ("seedling", "growing"):
        MODELS["plant_%s_%s_sick" % (s, stage)] = cigars.plant(s, stage, healthy=False)
    for kind in ("fresh", "dried", "aged"):
        MODELS["leaf_%s_%s" % (s, kind)] = cigars.leaf_item(s, kind)
    MODELS["seeds_" + s] = cigars.seeds(s)

for f in os.listdir(out):
    if f.endswith(".cs"):
        os.remove(os.path.join(out, f))
cls = lambda name: "M_" + name
for name, model in MODELS.items():
    open(os.path.join(out, cls(name) + ".cs"), "w", encoding="utf-8").write(model.to_csharp("CigarSmoking", cls(name)))
index = ["// <auto-generated> by tools/modelkit/build_cigars.py. Do not edit by hand. </auto-generated>", "namespace CigarSmoking", "{",
         "    internal static class ModelIndex", "    {", "        internal static object[][] Parts(string name)", "        {", "            switch (name)", "            {"]
for name in MODELS:
    index.append('                case "%s": return %s.Parts;' % (name, cls(name)))
index += ["            }", '            throw new System.ArgumentException("no model called " + name);', "        }", "    }", "}", ""]
open(os.path.join(root, "ModelIndex.cs"), "w", encoding="utf-8").write("\n".join(index))
print("models:", len(MODELS))

# the colours every model part names (the game's own wood, stone and iron are borrowed in the game instead)
from modelkit import PALETTE
palette = dict(PALETTE)
palette.update(cigars.PAL)
for borrowed in ("Planks", "Dark", "Iron", "Stone"):
    palette.pop(borrowed, None)
lines = ["// <auto-generated> by tools/modelkit/build_cigars.py. Do not edit by hand. </auto-generated>", "using System.Collections.Generic;", "using UnityEngine;", "",
         "namespace CigarSmoking", "{", "    internal static class Palette", "    {", "        internal static readonly Dictionary<string, Color> All = new Dictionary<string, Color>", "        {"]
for name, (r, g, bl) in sorted(palette.items()):
    lines.append('            { "%s", new Color(%.3ff, %.3ff, %.3ff) },' % (name, r, g, bl))
lines += ["        };", "    }", "}", ""]
open(os.path.join(root, "Palette.cs"), "w", encoding="utf-8").write(chr(10).join(lines))

# the pictures: items and pieces, 128 px, see-through
LEAF = dict(yaw=30, pitch=48, target=(0, 0.03, 0.0), dist=0.95)
PICS = {
    "rack": (cigars.rack(), dict(yaw=30, pitch=14, target=(0, 0.75, 0), dist=4.4)),
    "barrel": (cigars.barrel(), dict(yaw=30, pitch=16, target=(0, 0.5, 0), dist=3.2)),
    "table": (cigars.table(), dict(yaw=30, pitch=20, target=(0, 0.45, 0), dist=4.2)),
    "humidor": (cigars.humidor(), dict(yaw=28, pitch=16, target=(0, 0.38, 0), dist=2.4)),
}
for s in cigars.STRAINS:
    PICS["seeds_" + s] = (cigars.seeds(s), dict(yaw=25, pitch=40, target=(0, 0.03, -0.02), dist=0.5))
    PICS["plant_" + s] = (cigars.plant(s, "growing"), dict(yaw=25, pitch=15, target=(0, 0.24, 0), dist=1.9))
    for kind in ("fresh", "dried", "aged"):
        PICS["leaf_%s_%s" % (s, kind)] = (cigars.leaf_item(s, kind), LEAF)
for kind in cigars.TYPES:
    PICS["cigar_" + kind] = (cigars.cigar(kind), dict(yaw=0, pitch=62, target=(0, 0.01, 0), dist=0.5))
only = sys.argv[1:]
for name, (model, kw) in PICS.items():
    if only and name not in only:
        continue
    icon(model, os.path.join(icons, name + ".png"), px=128, palette=cigars.PAL, **kw)
print("icons:", len(PICS))

# the cover for the mod manager
if not only:
    cover = render(cigars.table(), size=(640, 360), yaw=30, pitch=18, target=(0, 0.55, 0), dist=4.2, scale=2, palette=cigars.PAL,
                   bg=((96, 78, 60), (34, 28, 22)), floor=(74, 60, 44))
    cover.convert("RGB").save(os.path.join(root, "cover.png"), optimize=True)
