"""
modelkit: describe a 3D model as simple shapes (boxes, cylinders, spheres), preview it as a picture, and write the
same description out as C# for the Valheim mods to build in the game.

The shapes follow Unity's own primitives, so what you see in the preview is what the game builds:
  cube      1 x 1 x 1, scaled by (sx, sy, sz)
  cylinder  diameter sx / sz, and HALF height sy (a scale of y=1 is a 2 m tall cylinder)
  sphere    diameter 1, scaled by (sx, sy, sz)
Positions are metres, y up, the front of a piece faces -z. Rotations are Unity euler angles (z, then x, then y).
"""
import math
import numpy as np
from PIL import Image, ImageDraw, ImageFilter

# ---------------------------------------------------------------- model description

class Part:
    def __init__(self, name, shape, pos, scale, euler, mat, parent):
        self.name, self.shape, self.pos, self.scale, self.euler, self.mat, self.parent = name, shape, pos, scale, euler, mat, parent


class Model:
    def __init__(self):
        self.parts = []
        self._group = None  # name of the group new parts go into
        self.scale = 1.0     # the whole model is shrunk or grown by this when the game builds it

    def _add(self, name, shape, pos, scale, euler, mat):
        self.parts.append(Part(name, shape, pos, scale, euler, mat, self._group))

    def box(self, name, x, y, z, sx, sy, sz, mat, rx=0, ry=0, rz=0):
        self._add(name, "Cube", (x, y, z), (sx, sy, sz), (rx, ry, rz), mat)

    def cyl(self, name, x, y, z, diameter_x, half_height, diameter_z, mat, rx=0, ry=0, rz=0):
        self._add(name, "Cylinder", (x, y, z), (diameter_x, half_height, diameter_z), (rx, ry, rz), mat)

    def sph(self, name, x, y, z, sx, sy, sz, mat, rx=0, ry=0, rz=0):
        self._add(name, "Sphere", (x, y, z), (sx, sy, sz), (rx, ry, rz), mat)

    def mesh(self, name, verts, faces, colours):
        """Real triangles (already in blueprint coordinates) with an RGB colour (0-255) per triangle."""
        self._add(name, "Mesh", (0, 0, 0), (1, 1, 1), (0, 0, 0), "")
        self.parts[-1].verts, self.parts[-1].faces, self.parts[-1].colours = verts, faces, colours

    def box_rot(self, name, center, size, rot, mat):
        """A box turned by a 3x3 rotation matrix (used for pieces read from the game's data)."""
        self._add(name, "Cube", tuple(center), tuple(size), (0, 0, 0), mat)
        self.parts[-1].rot = rot

    def quad(self, name, x, y, z, width, height, mat, rx=0, ry=0, rz=0):
        """A flat picture facing -z (Unity's Quad): width x height metres."""
        self._add(name, "Quad", (x, y, z), (width, height, 1), (rx, ry, rz), mat)

    def begin_group(self, name, x=0, y=0, z=0, rx=0, ry=0, rz=0):
        """Parts added until end_group are children of an empty object at this spot (e.g. a reel that spins)."""
        self.parts.append(Part(name, "Group", (x, y, z), (1, 1, 1), (rx, ry, rz), "", self._group))
        self._group = name

    def end_group(self):
        parent = None
        for p in self.parts:
            if p.name == self._group:
                parent = p.parent
        self._group = parent

    # ---- C# output
    def to_csharp(self, namespace, cls="ModelData"):
        names = [p.name for p in self.parts]
        # group names must be unique for the parent lookup; parts can repeat names
        lines = ["// <auto-generated> by tools/modelkit. Edit the model script and regenerate; do not edit by hand. </auto-generated>",
                 "namespace %s" % namespace, "{",
                 "    internal static class %s" % cls, "    {",
                 "        internal const float Scale = %sf;" % ("%.3f" % self.scale).rstrip("0").rstrip("."),
                 "        // name, shape, parent group (or \"\"), x, y, z, scale x, y, z, euler x, y, z, material",
                 "        internal static readonly object[][] Parts =", "        {"]
        for p in self.parts:
            f = lambda v: ("%.4f" % v).rstrip("0").rstrip(".") + "f" if abs(v) > 1e-9 else "0f"
            lines.append('            new object[] { "%s", "%s", "%s", %s, %s, %s, %s, %s, %s, %s, %s, %s, "%s" },' % (
                p.name, p.shape, p.parent or "", f(p.pos[0]), f(p.pos[1]), f(p.pos[2]),
                f(p.scale[0]), f(p.scale[1]), f(p.scale[2]), f(p.euler[0]), f(p.euler[1]), f(p.euler[2]), p.mat))
        lines += ["        };", "    }", "}", ""]
        return "\n".join(lines)


# ---------------------------------------------------------------- maths

def euler_matrix(rx, ry, rz):
    """Unity order: rotate about z, then x, then y."""
    ax, ay, az = [math.radians(a) for a in (rx, ry, rz)]
    cx, sx, cy, sy, cz, sz = math.cos(ax), math.sin(ax), math.cos(ay), math.sin(ay), math.cos(az), math.sin(az)
    Rx = np.array([[1, 0, 0], [0, cx, -sx], [0, sx, cx]])
    Ry = np.array([[cy, 0, sy], [0, 1, 0], [-sy, 0, cy]])
    Rz = np.array([[cz, -sz, 0], [sz, cz, 0], [0, 0, 1]])
    return Ry @ Rx @ Rz


def world_matrices(model):
    """4x4 world matrix for each part (children inherit their group's transform)."""
    local = {}
    result = []
    by_name = {}
    for p in model.parts:
        m = np.eye(4)
        R = euler_matrix(*p.euler)
        S = np.diag(p.scale)
        if getattr(p, "rot", None) is not None:
            R = p.rot
        m[:3, :3] = R @ S
        m[:3, 3] = p.pos
        parent = by_name.get(p.parent) if p.parent else None
        w = (parent @ m) if parent is not None else m
        if p.shape == "Group":
            w = w.copy()
            by_name[p.name] = w
        result.append(w)
    return result


# ---------------------------------------------------------------- meshes (unit shapes, flat or smooth normals)

def mesh_cube():
    tris, norms = [], []
    faces = [((1, 0, 0), (0, 1, 0), (0, 0, 1)), ((-1, 0, 0), (0, 0, 1), (0, 1, 0)),
             ((0, 1, 0), (0, 0, 1), (1, 0, 0)), ((0, -1, 0), (1, 0, 0), (0, 0, 1)),
             ((0, 0, 1), (1, 0, 0), (0, 1, 0)), ((0, 0, -1), (0, 1, 0), (1, 0, 0))]
    for n, u, v in faces:
        n, u, v = np.array(n, float), np.array(u, float), np.array(v, float)
        c = n * 0.5
        q = [c - u * .5 - v * .5, c + u * .5 - v * .5, c + u * .5 + v * .5, c - u * .5 + v * .5]
        tris += [[q[0], q[1], q[2]], [q[0], q[2], q[3]]]
        norms += [[n, n, n], [n, n, n]]
    return np.array(tris), np.array(norms)


def mesh_cylinder(seg=24):
    tris, norms = [], []
    for i in range(seg):
        a0, a1 = 2 * math.pi * i / seg, 2 * math.pi * (i + 1) / seg
        p0, p1 = np.array([math.cos(a0) * .5, 0, math.sin(a0) * .5]), np.array([math.cos(a1) * .5, 0, math.sin(a1) * .5])
        n0, n1 = np.array([math.cos(a0), 0, math.sin(a0)]), np.array([math.cos(a1), 0, math.sin(a1)])
        up, dn = np.array([0, 1, 0.]), np.array([0, -1, 0.])
        a, b, c, d = p0 + dn, p1 + dn, p1 + up, p0 + up
        tris += [[a, b, c], [a, c, d]]
        norms += [[n0, n1, n1], [n0, n1, n0]]
        tris += [[up, d, c], [dn, b, a]]
        norms += [[up, up, up], [dn, dn, dn]]
    return np.array(tris), np.array(norms)


def mesh_sphere(lat=12, lon=20):
    tris, norms = [], []
    def pt(i, j):
        th, ph = math.pi * i / lat, 2 * math.pi * j / lon
        n = np.array([math.sin(th) * math.cos(ph), math.cos(th), math.sin(th) * math.sin(ph)])
        return n * .5, n
    for i in range(lat):
        for j in range(lon):
            (a, na), (b, nb), (c, nc), (d, nd) = pt(i, j), pt(i, j + 1), pt(i + 1, j + 1), pt(i + 1, j)
            tris += [[a, b, c], [a, c, d]]
            norms += [[na, nb, nc], [na, nc, nd]]
    return np.array(tris), np.array(norms)


def mesh_quad():
    bl, br, tr, tl = np.array([-.5, -.5, 0]), np.array([.5, -.5, 0]), np.array([.5, .5, 0]), np.array([-.5, .5, 0])
    n = np.array([0, 0, -1.0])
    return np.array([[bl, br, tr], [bl, tr, tl]]), np.array([[n, n, n], [n, n, n]])


# A tobacco leaf: base at the origin, tip at z = 1, 1 wide, ovate with a pointed tip, a raised midrib, ruffled edges and a drooping tip.
# The same formulas are in mods/CigarSmoking/Meshes.cs: change both together.
LEAF_NT, LEAF_NU = 12, 6


def leaf_half_width(t):
    return 0.5 * (max(0.0, math.sin(math.pi * t ** 0.8)) ** 0.75) * (1 - 0.3 * t)


def leaf_y(t, u, lift=0.0):
    return 0.10 * (1 - abs(u)) - 0.16 * t * t + 0.03 * math.sin(13 * t + 2.5 * u) * abs(u) ** 2 + lift


def _grid_to_tris(grid, double=True):
    """grid[i][j] -> points; triangles on both sides (the leaf is paper thin, so it has to be seen from either side)."""
    tris, norms = [], []
    for i in range(len(grid) - 1):
        for j in range(len(grid[0]) - 1):
            a, b, c, d = grid[i][j], grid[i][j + 1], grid[i + 1][j + 1], grid[i + 1][j]
            for t3 in ((a, b, c), (a, c, d)):
                n = np.cross(t3[1] - t3[0], t3[2] - t3[0])
                ln = np.linalg.norm(n)
                if ln < 1e-12:
                    continue
                n = n / ln
                if n[1] < 0:
                    n = -n
                tris.append(list(t3)); norms.append([n, n, n])
                if double:
                    tris.append([t3[0], t3[2], t3[1]]); norms.append([-n, -n, -n])
    return np.array(tris), np.array(norms)


def mesh_leaf():
    grid = []
    for i in range(LEAF_NT + 1):
        t = i / LEAF_NT
        w = leaf_half_width(t)
        grid.append([np.array([(-1 + 2 * j / LEAF_NU) * w, leaf_y(t, -1 + 2 * j / LEAF_NU), t]) for j in range(LEAF_NU + 1)])
    return _grid_to_tris(grid)


def mesh_rib():
    """The midrib and six pairs of side veins as thin ribbons lying just above the leaf."""
    tris, norms = [], []
    def ribbon(points, width):
        left, right = [], []
        for k, p in enumerate(points):
            q = points[min(k + 1, len(points) - 1)] - points[max(k - 1, 0)]
            side = np.cross([0, 1, 0], q)
            side = side / (np.linalg.norm(side) + 1e-9) * width / 2
            left.append(p - side); right.append(p + side)
        return _grid_to_tris([[l, r] for l, r in zip(left, right)])
    def on_leaf(t, u):
        return np.array([u * leaf_half_width(t), leaf_y(t, u, 0.012), t])
    mid = [on_leaf(i / 10 * 0.96, 0.0) for i in range(11)]
    t1, n1 = ribbon(mid, 0.035)
    tris += list(t1); norms += list(n1)
    for k in range(1, 7):
        for sgn in (-1, 1):
            t0 = 0.08 + k * 0.12
            pts = [on_leaf(min(0.97, t0 + 0.14 * s / 4), sgn * 0.9 * s / 4) for s in range(5)]
            tv, nv = ribbon(pts, 0.016)
            tris += list(tv); norms += list(nv)
    return np.array(tris), np.array(norms)


QUAD_UV = np.array([[[0, 0], [1, 0], [1, 1]], [[0, 0], [1, 1], [0, 1]]], float)

MESHES = {}

def unit_mesh(shape):
    if shape not in MESHES:
        MESHES[shape] = {"Cube": mesh_cube, "Cylinder": mesh_cylinder, "Sphere": mesh_sphere, "Quad": mesh_quad, "Leaf": mesh_leaf, "Rib": mesh_rib}[shape]()
    return MESHES[shape]


# ---------------------------------------------------------------- rendering

PALETTE = {
    "Planks": (0.55, 0.37, 0.21), "Dark": (0.27, 0.18, 0.11), "Iron": (0.42, 0.43, 0.47), "Stone": (0.52, 0.52, 0.53),
    "Coal": (0.15, 0.15, 0.17), "Parchment": (0.90, 0.82, 0.63), "Ink": (0.16, 0.11, 0.08), "Bone": (0.92, 0.89, 0.80),
    "Red": (0.66, 0.10, 0.08), "Gold": (0.93, 0.72, 0.20), "Leather": (0.42, 0.26, 0.13), "Glow": (1.0, 0.72, 0.28),
    "Teal": (0.25, 0.75, 0.8), "Cream": (0.95, 0.92, 0.84), "Green": (0.18, 0.5, 0.25), "Blue": (0.2, 0.35, 0.7),
    "Chrome": (0.78, 0.8, 0.84), "StoneDark": (0.36, 0.36, 0.38), "Black": (0.06, 0.06, 0.07), "RedDark": (0.38, 0.05, 0.05), "GlowB": (1.0, 0.45, 0.2),
}
GLOWING = {"Glow", "GlowB"}


def render(model, size=(900, 900), yaw=28, pitch=14, target=(0, 1.1, 0), dist=7.0, fov=28, scale=2, bg=None, ground=True, transparent=False, palette=None, atlas=None, floor=None):
    pal = dict(PALETTE)
    if palette:
        pal.update(palette)
    W, H = size[0] * scale, size[1] * scale
    img = np.zeros((H, W, 4), np.float32)
    zbuf = np.full((H, W), 1e9, np.float32)

    yawr, pr = math.radians(yaw), math.radians(pitch)
    tgt = np.array(target, float)
    eye = tgt + dist * np.array([math.sin(yawr) * math.cos(pr), math.sin(pr), -math.cos(yawr) * math.cos(pr)])
    fwd = tgt - eye; fwd /= np.linalg.norm(fwd)
    right = np.cross([0, 1, 0], fwd); right /= np.linalg.norm(right)
    up = np.cross(fwd, right)
    f = 1.0 / math.tan(math.radians(fov) / 2)

    def project(P):
        d = P - eye
        x, y, z = d @ right, d @ up, d @ fwd
        sx = (x * f / z) * (H / 2) + W / 2
        sy = H / 2 - (y * f / z) * (H / 2)
        return sx, sy, z

    L = np.array([-0.45, 0.80, -0.55]); L /= np.linalg.norm(L)
    L2 = np.array([0.6, 0.3, -0.4]); L2 /= np.linalg.norm(L2)

    if bg is None:
        bg = ((46, 52, 66), (22, 24, 32))
    if not transparent:
        top, bot = np.array(bg[0], np.float32), np.array(bg[1], np.float32)
        grad = np.linspace(0, 1, H)[:, None, None]
        img[:, :, :3] = (top * (1 - grad) + bot * grad) / 255.0
        img[:, :, 3] = 1.0

    mats = world_matrices(model)
    rng = np.random.RandomState(7)

    tex_all = None
    if atlas is not None:
        tex_all = np.array(Image.open(atlas).convert('RGB'))

    def draw_tris(tv, tn, color, glow=False, shade=True, uvs=None, tex=None):
        sx, sy, z = project(tv.reshape(-1, 3))
        sx, sy, z = sx.reshape(-1, 3), sy.reshape(-1, 3), z.reshape(-1, 3)
        for k in range(len(tv)):
            xs, ys, zs = sx[k], sy[k], z[k]
            if (zs <= 0.1).any():
                continue
            minx, maxx = int(max(0, math.floor(xs.min()))), int(min(W - 1, math.ceil(xs.max())))
            miny, maxy = int(max(0, math.floor(ys.min()))), int(min(H - 1, math.ceil(ys.max())))
            if minx > maxx or miny > maxy:
                continue
            den = (ys[1] - ys[2]) * (xs[0] - xs[2]) + (xs[2] - xs[1]) * (ys[0] - ys[2])
            if abs(den) < 1e-9:
                continue
            gx, gy = np.meshgrid(np.arange(minx, maxx + 1) + 0.5, np.arange(miny, maxy + 1) + 0.5)
            w0 = ((ys[1] - ys[2]) * (gx - xs[2]) + (xs[2] - xs[1]) * (gy - ys[2])) / den
            w1 = ((ys[2] - ys[0]) * (gx - xs[2]) + (xs[0] - xs[2]) * (gy - ys[2])) / den
            w2 = 1 - w0 - w1
            inside = (w0 >= 0) & (w1 >= 0) & (w2 >= 0)
            if not inside.any():
                continue
            depth = w0 * zs[0] + w1 * zs[1] + w2 * zs[2]
            sub = zbuf[miny:maxy + 1, minx:maxx + 1]
            mask = inside & (depth < sub)
            if not mask.any():
                continue
            n = (w0[..., None] * tn[k][0] + w1[..., None] * tn[k][1] + w2[..., None] * tn[k][2])
            n /= np.linalg.norm(n, axis=2, keepdims=True) + 1e-9
            if glow:
                col = np.broadcast_to(np.array(color) * 1.0, n.shape).copy()
            else:
                diff = np.clip(n @ L, 0, 1)
                fill = np.clip(n @ L2, 0, 1) * 0.25
                # ambient light: brighter from above, darker underneath (a cheap stand-in for occlusion)
                amb = 0.30 + 0.16 * (n[..., 1] * 0.5 + 0.5)
                lit = amb + 0.78 * diff + fill
                basecol = np.array(color)[None, None, :]
                if tex is not None:
                    uv = w0[..., None] * uvs[k][0] + w1[..., None] * uvs[k][1] + w2[..., None] * uvs[k][2]
                    th, tw = tex.shape[:2]
                    tx_ = np.clip((uv[..., 0] * tw).astype(int), 0, tw - 1)
                    ty_ = np.clip(((1 - uv[..., 1]) * th).astype(int), 0, th - 1)
                    basecol = tex[ty_, tx_] / 255.0
                col = basecol * lit[..., None]
                # a touch of shine
                hv = L + (-fwd); hv /= np.linalg.norm(hv)
                spec = np.clip(n @ hv, 0, 1) ** 24 * 0.12
                col = col + spec[..., None]
            sub[mask] = depth[mask]
            region = img[miny:maxy + 1, minx:maxx + 1]
            region[mask, :3] = np.clip(col[mask], 0, 1)
            region[mask, 3] = 1.0

    # soft shadow on the floor
    if ground:
        ty, tx = np.mgrid[0:H, 0:W]
        # floor plane y=0: intersect each pixel's ray
        ndc_x = (tx + 0.5 - W / 2) / (H / 2) / f
        ndc_y = (H / 2 - ty - 0.5) / (H / 2) / f
        ray = fwd[None, None, :] + ndc_x[..., None] * right + ndc_y[..., None] * up
        with np.errstate(divide="ignore", invalid="ignore"):
            t = -eye[1] / ray[..., 1]
        hit = (t > 0) & np.isfinite(t)
        px = eye[0] + t * ray[..., 0]
        pz = eye[2] + t * ray[..., 2]
        # extent of the model on the floor for the shadow size
        allp = []
        for p, w in zip(model.parts, mats):
            if p.shape == "Mesh":
                allp.extend(list(p.verts[:: max(1, len(p.verts) // 8)]))
            elif p.shape != "Group":
                allp.append(w[:3, 3])
        allp = np.array(allp)
        cx, cz = (allp[:, 0].min() + allp[:, 0].max()) / 2, (allp[:, 2].min() + allp[:, 2].max()) / 2
        rx_, rz_ = (allp[:, 0].max() - allp[:, 0].min()) / 2 + 0.5, (allp[:, 2].max() - allp[:, 2].min()) / 2 + 0.5
        dd = ((px - cx) / rx_) ** 2 + ((pz - cz) / rz_) ** 2
        shadow = np.clip(1 - dd, 0, 1) ** 1.5 * 0.55
        shadow = np.where(hit, shadow, 0)
        if floor is not None and not transparent:
            # a patch of ground under the design, fading out at the edges
            fd = ((px - cx) / (rx_ * 1.6)) ** 2 + ((pz - cz) / (rz_ * 1.6)) ** 2
            fa = np.where(hit, np.clip(1.3 - fd, 0, 1), 0)[..., None]
            img[:, :, :3] = img[:, :, :3] * (1 - fa) + (np.array(floor, np.float32) / 255.0) * fa
        if not transparent:
            img[:, :, :3] *= (1 - shadow[..., None])
        else:
            img[:, :, 3] = np.maximum(img[:, :, 3], shadow * 0.6)

    for part, w in zip(model.parts, mats):
        if part.shape == "Group":
            continue
        if part.shape == "Mesh":
            mv, mf, cols = part.verts, part.faces, part.colours   # (not "f": that name is the camera's focal length)
            if len(mf) == 0:
                continue
            tv = mv[mf]                                 # (F, 3, 3)
            n = np.cross(tv[:, 1] - tv[:, 0], tv[:, 2] - tv[:, 0])
            n /= np.linalg.norm(n, axis=1, keepdims=True) + 1e-9
            # light both sides of a face the same (the game's meshes are seen from either side in previews)
            facing = np.einsum("ij,j->i", n, -fwd) < 0
            n[facing] *= -1
            tn = np.repeat(n[:, None, :], 3, axis=1)
            keys = cols[:, 0].astype(np.int64) * 65536 + cols[:, 1].astype(np.int64) * 256 + cols[:, 2]
            for key in np.unique(keys):
                sel = keys == key
                colour = np.array([(key >> 16) & 255, (key >> 8) & 255, key & 255]) / 255.0
                draw_tris(tv[sel], tn[sel], colour * 1.15)
            continue
        tris, norms = unit_mesh(part.shape)
        A = w[:3, :3]
        tv = tris @ A.T + w[:3, 3]
        try:
            Ninv = np.linalg.inv(A).T
        except np.linalg.LinAlgError:
            continue
        tn = norms @ Ninv.T
        tn /= np.linalg.norm(tn, axis=2, keepdims=True) + 1e-9
        base = np.array(pal.get(part.mat, (0.8, 0.2, 0.8)))
        jitter = 1.0 + (hash(part.name) % 13 - 6) * 0.009
        uvs = tex = None
        if part.shape == "Quad" and part.mat.startswith("Sym") and tex_all is not None:
            i = int(part.mat[3:]); cell = tex_all.shape[0]
            tex = tex_all[:, i * cell:(i + 1) * cell]; uvs = QUAD_UV
        draw_tris(tv, tn, base * jitter if part.mat not in GLOWING else base, glow=part.mat in GLOWING, uvs=uvs, tex=tex)

    out = Image.fromarray((np.clip(img, 0, 1) * 255).astype(np.uint8), "RGBA" if transparent else "RGBA")
    out = out.resize(size, Image.LANCZOS)
    return out


def contact_sheet(model, path, size=(640, 640), views=((28, 14), (-30, 14), (0, 8), (90, 14)), **kw):
    """Four views side by side (front-right, front-left, straight front, side)."""
    imgs = [render(model, size=size, yaw=y, pitch=p, **kw) for y, p in views]
    cols = 1 if len(imgs) == 1 else 2
    rows = (len(imgs) + cols - 1) // cols
    sheet = Image.new("RGBA", (size[0] * cols, size[1] * rows))
    for i, im in enumerate(imgs):
        sheet.paste(im, ((i % cols) * size[0], (i // cols) * size[1]))
    sheet.convert("RGB").save(path)
    return path


def icon(model, path, px=256, yaw=24, pitch=12, **kw):
    """A square picture with a see-through background, for the build menu."""
    im = render(model, size=(px, px), yaw=yaw, pitch=pitch, transparent=True, ground=False, **kw)
    im.save(path)
    return path
